---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb-operator

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./helmrepository.yaml
  - ./mariadb-operator-crds/ks.yaml
  - ./mariadb-operator/ks.yaml
