---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-media
  namespace: radarr
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Ti
  volumeName: radarr-media
