---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-media
spec:
  capacity:
    storage: 10Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.0.10.50
    path: /mnt/storage/media
