apiVersion: v1
kind: Secret
metadata:
  name: radarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:RJkuzXUf+elKTMcLikTFrMdUlbpbTB/2WBAmpNZ4MWE=,iv:dxfMbKdLkra487hH9XrWPDuPhMdwGf+LeGnnFvwAAkA=,tag:GAURTqcacsp1f+6hrey2pg==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHhwaTM5cm5EN0daV0pj
        N2MxQWp5eEVzcjkxWStjaGJlbjlsNmJLblFjClgvcnNHSldZenpWSmovSG44b2RO
        Yy9FS3NzbjlEMVQvZnliYndxYVhNL1EKLS0tIDh1MEVOS2hNNGE5WThVT09na0Ez
        WXU1TVFSNytrc2dTa1U3TCtPenRaeDAKOE/Tq1qVfk6WY209bp1V0Kb4JGXGKjJZ
        ZeTKu5MVnYwFvEX6N3gZoPOaCD9uEya6syGWqNx+hRqovi2WPrSetQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T02:37:47Z"
  mac: ENC[AES256_GCM,data:M3xxOEHZ/HIOaYukAtgycnDgAEZaar4llkTXeRr837TVdDvqqDZi0uaDHNR61w9gZP4okpp3wcDHdvl6oJqza28TSRZbIMTow82UO8zG1f+pJKi9ODMAd3OyQJPBiMx75gLpUFqzs+KpadcnYqiZJm2VV+MIEIprErcnuwi/Ii4=,iv:Bw9xEz7AuG1GaHXhl/F+4ZzENGtSMyUkVcqKb18b5Z4=,tag:wfjr/wCuHl7Nm9kDDLWP9w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
