apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:ThZfZNquU3XpME9/GmTTXE8dFahxa0epokNAjyB8+FzK+6qYcq1dj8WHP9Q=,iv:39dwyfUyVmILNQYthGYEbObS8+6ZtyyxE7KH/i0Jl0M=,tag:rdnu3dYyodYqPC/+gpjB+g==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1bHJ5eC9ENEZsRkNnTmtL
        YjNmQk9kbGtBbkxpbnBuSGQvSk0zWW0ySkR3Cjg1SnFmdjQ2RGVKZm05bTlFbkNP
        QlpaemdKejlNQkRlTkhWeVZwbXVFcWMKLS0tIERIZ1lTeUNacnEwVitiZStlaWFz
        bjMrMjJmcEdSYThCdjNIU1BXa3BzQ2sKBtpcZ+t3mLeefA/1wgErj4h1vGY2QaxK
        m5hAgk8Z1/pN3uOSCVHweXp1Y1RxAG3iPP3D2sfnYReEMoKzMv/XOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T00:38:01Z"
  mac: ENC[AES256_GCM,data:1UPfd9wWHKeS3la81iOsFv8HGiATJMHbNyxLN9i96U/wrPKyUcgKz18QrQRRXKjP5GOkF2DqUJPrLqTjRFAE5qWvQOmwRE25Sd+6JCMHJRQ39xU+C7Do8sqwXIVHmrs8CeHpq102ngWaIZhXg0dPdgfe7sCvoc40G4yOkwcxqZs=,iv:L6K+O5/ZcS7pmqqoGNbgpTlseOPbdIP4iW9YaWI95rI=,tag:YzVGsdb6/l9oFqPPLauvpA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
