apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-driver-config
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:kYKF5XKhwsu1+ITJPuohX8PBcCCoWQQOHcj6/O4SHlPzRvSYnCz2TLXRj+TOk5+XRKvzhAEK9BjP7IHBgOCVEsMI64JUhq6Vew5EbiNABj0QcWD+Pc2Yz8lVtwNK6i38GxHleVOTF2bibVLS0u645B7Xybp35qWV8kmE0Y4z+LHrf7ShssBkLHJZY6XTZIgAAAUSPKxYcEORUI+c/7UzLNNc/JjBxU/csJUxpfZnaoo2t/M//y+Jc1GxTN4Zka1udeFOqIgTNdd2tVVsIyyPUcM7VDmAm5/pjFHdPYuZNrkelhbwL0TrN8q48lfjfHqFgSW/jE+T9n+1ZbOMk6u5Keu37b4Nx27yYF6903HM+DVGQSTXCJf80BL0aUilnw4halu1cqXVO/IgzAXuXd3gzQQoNZJBra+3eo2MbafhdfWeRSK7BDk0D8O3km8tjzoKovhP2S20Sxb2Y6aUtzpLsD0l/fAaZ6BRT8nAFwU2gYrtAXtGnXT0qf5cb1EZfKfm5Yr9qXUBcSV7GsZmwBA1g3vzl1lW87qdjqdVYoCXpalhIvKe+lgl03TMM4ov5BUAWVfP0Id1VZ4s/6qSrCRC6lFxqSUvQVKKLQkr6yWnz920/Tvj2Ct2OBTjMsk7oeplig0XgoR6ZigcSGf2c4QxhjnxD3e70zzkPhW4Yaj1IaeYzld6Jo8LuK9ailyzfublpACFGGYwZvsG8SOckxKLJu32SXVJiCjkoGbQsiZguFgBDNkk1/28ncdabnQeRqJZ71gGYauu/RgNlskNOq3n9lbHBqwbQ+EnxA0LILGfbOecg/iXM5/+YLv1zHnYz0PpZ6owf0dqP/Wu3K33N4e8PDtfnk9j9/kDMCSZEe7OUGZsGWt8++kfSwPSSC+bvRDWdjjifEw1Pd6VJB/kIGc2nVecNAoy3x1wsWWCzAyNwibjLddj7cNfWVn870Hq2LAfPcJ7tr+siPYILgMC239barkjhNU45y4YuosefCb3tgVnFDDPD6AD7MDqOhSlEk2UJg5yNnfFObvy5Awgvx7wM24294rdnB0KmmNGLiKNUJuPPzFYRSJq73QarCncAYogRwHg3Lbbmua9kynw5fOdogH7I+TarWh8Vp0u7ib0gYA4RVBTiAQq82+vfndEUR/N2vvXKfR6Lq8Tx+iO/ecAnymCbfLqeI4i46ZcJhUu6WAcaMZpI2G2EMk2xr+nWp8o9w9i0gDmVzqrc2pEO/8BgKRGO5fAR+4fIxbLWBazX+RIvYf9fC1g2mCsYe/xnPGJd/alxY5bWG/yjmuHb3+qBfw2fp6t3Ssd/ekKRi7Ky1+DXEeq,iv:cEicioGxJ+rf4jZQkUHkXJlEhf1+saOnjKWRIpXZYsA=,tag:R8tHw2uKXSYC5Vw3TPaMPg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
            SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
            ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
            SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
            n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-07T23:10:47Z"
    mac: ENC[AES256_GCM,data:4oZbG4FvJf/OoN3KRz8CoT/1D6C135IxgWlWpSjMJvsnaZgk9CHGdQC5n0urblN0FqCjsSeKcP8QEeqod7BMNDeCHxHIcIkRDsXdAwyvAYL6HNsINdZOAGz710rtRHut/WxFyeV/jlEo8cBbQu9+wCg4skjlvgPFQ7UFPBrMOaM=,iv:SmH5xkj0BLnfAQyqamlDLboOC64JBmK/sRgZXjcwsbo=,tag:KM0kBTPUZxu0yruXU4uGcw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
