apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-driver-config
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:IwEHJpHtYiispTOMGp3JfLnbJWhPh5TwKCNYKo67qaT8OBGC3GUqE7y/91l6VFHp9tGJ6AaSIN6EbbkQnWsHRwubyM2XLMlRZKSGGMUu9tzkb5afyPS88fBIxuedNCeIZzFMzUBCuI2xgp4M58nyAMvBHTB8ftGOQPPV2JqOnRRPgYSIr6xxuI1f8rDWkXdT1oO+aOopTrMjzQddq2/ky2Ik/jFZ7ZdhS+ddNB71Q/WKRdqTADI2J3uU8FxPQLSwq4eGdwWm8qgqhRiVhDNFc2B1k84kYyS4lFOe3exZVYiuufiy1FDWjOyPwyPSeEYyIzSbnVTZCz882pttaDm6vyDXTnCMvnSWF7BQiPzoEzLkADtpFrAMIVVGeFYpLAMYGFSFcNRZkJeEWl1AXQeBnuUxZYZyXlsGUneIWB1D/b7AinTQ01QebsZNB7rZ/nVDwWB16ZbmJJ9WoMlV5bWQkRrOnj4eP5ztN/goEHtFLcHYtqJPUIjfdlxhwFhli+VysXj6PIznJa+oBfyoOcelWmH1OqaRTyDcu2fd20tlKeCrGmyZhzNWSO/qnynmN14PDewJ4WIiVVmm3PQFycmItgaYjC4YJU4iXYjCfAIpbewKZsuPpWehl3mPsX1Ckarmn5sbtCBnCt9cue933/ZeyLeT+YfszrOPGkUBXQxgW0GIl09oiifQl4ea4L39RNYlrIX0s7DRSaEhEBNRjPjRfZEvDmhm3Qaf3A0r80ICN4/hwprYR4bHRxL36V2hx7T5Cb9JgKsH6oSj9yF9G10bLjQtfuf9kEwvJixpD3JneclMcPRIQRPudaXPhJpenE5VpPtKuJJomIXmghh3mrdeGkPe/G6XiGxJxeZTw62VNtqJvoFA6eDui/bNupna7UNEaGuAlEwyYXTt36qdYWR8RxLFZ3vA0W4T1qGdpYUNhp3Vtff1WHNS0HUCk89i2ZQ58AQTbT12NGC5M5dT7hpN1ekw8kq2GFDJEd0ZBoeMuj4NF7nn/3SxJDEWBXGREqrXNUdiF6A42D5eqh7rA85xYUMGNpLKeyzPS2uc0tH5+4C7Fm+BYS1Un9a8ZEY2dBckBKGaOVoRTaYbIa7IqbMYIgK2e/NKCT+ThZvGxWfDrwtaWyilRACBHlu3lgBwWeJrPX7og3/gs/JOIne4AY/1G9PQy9FVJcCoB5trM1LPh6jgPKUjg7ZgHPO54rOEmongrOKvuOmMeR/bvdoSrYBZvzVsUXoHkRb3/92bYEqCg7onjIVxQMs3CU6n1B/EB6iJayGR+HUsTnI1Q6rDd5KdvcA3oZwSpfh+UMdwl7tDqYAo64vGv/pciYcYqRGT2FNpYH4JOVrcKIIi,iv:NQ47UECLPNYCydZmxazJTab+aQhPD+GO+iCwY0dCa1o=,tag:oEl1Znhc+bYlY28Bw+aZTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
            SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
            ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
            SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
            n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T19:48:21Z"
    mac: ENC[AES256_GCM,data:pC2l6wVovKrtlZU6z19CEOdZmKUPMW9S4KBytazfizg7pRCY83X6cPC+VhC8+1UG1NLbOaX473U+yZQNQ0yw7pemZMH2GPOJ6ICbhzdP44iq3+wrTiOMKt0jcdKaLzOEbSOfJ3mzQFJrPObMhoMpPNYt8NP6mqhvG6XGLyB6/0w=,iv:KABRnZKrEYTF2xqSCFqU/GETyagWv3WItqj2VEhAXjw=,tag:O1I3TvZmB5RTDxWGbYZlKQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
