apiVersion: v1
kind: Secret
metadata:
  name: freenas-api-iscsi-driver-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:7mbtghWITJqiOJMha1CRJcSRjamptr9d6DK+pBYYMSst1HVnRUX/gEJFZX/y6+w6tDhNPHwc255rhCLGnZU07xp/RAuMc+UC17TJyogTyX2fgTeRjVxe2o7HiHM6N9R4x8P7+lsNiIXQJnCVnKBVfF3XnFNXIXMpsJ7SMoBym8j6yOEcLMtPI6kht66cAalenTOtDIdqm6mIw69OzYgZKu6FN55pflUoXTdonBhUQTW+Opz1CpndrrPp8JzTY3H8ecgE6WN8sGO9pt2DNHldK8/ZIf7JRQ8erxlQE8FyCQPK4iOMHiF28tS+6IjgBWRxQjDNVXKErhwkoXxWd4CkYrXix1VwURT+EGvGcqiRCexjuCudwyt8Gt2jWE9bGV9dzqAGDnK0r494jMsT4f5WdfYpGh2BBacKF7ghWBxYUSR6ZOYJrSodZwirFRsXB9Ku/t0/M3bfCHRzYsuUvaMVesaDpibHL5oRTH5F16HK/GQ0N9m41DWUwHfxYvpTjCzrSzJQfHX6KGwWNOhecFY3LG+7bmd2bXSrvHebmwTSVAQHMd3SDl1OudQWH58N5iEzSwJxKYu2E29/DwXenqVBTfqH3woCpgbdFBTVQKnnEoYSOBwtwpl2VpdGzCxJpv4QKY2Efy8ezjN0Z3FdFUs6ZDKvOrFFk5UjjTCGQ1dNsofEA+N7K4FtSvnUB7IHJqzVgEQ1aiZy7geEXdm+nR+CNY5T1mLMvmzGXGHceR9FHQr6ZdK52eYQuCxAsPSh4fcENp0b2HRr2pOLqMhWyQlY8JoFzpsGy5S4JfgF9+Q4q3u/goZtnwFWwEiIcLKx83fVCDxzr6SkCzzRrCdErnI2sAhbWG3myKooCR/Gcm+uyJiNIXFa0Oh/MnG4nwjCOYxmu2LOAsWPn/dfk9XyI1Cn1yuT8x5zC/HpDe5va2I92B+i9neWe9wJ9SoXV4UGLYg5GtNGVVpqKuaR78A+zPdoFAkXeds5tFKngfpjTC2hPL3LUXOuXkcmy/MeaMTnOH//kaYceFT7rEbD/5xpaYDoi7GUpwoA5QU2eoNQK/3TEQh1XUls8WKpSQUZZmgGMmAGOuuQkJ336K0KmvLCZ/ef8sa8dfdKEvj1xMSL955im+scBQAalPBxBQuyyQRsKU94EzAGbYQjJkDCdn9jMeHFVlZLWhSNaDBxZoi2yEkrWb4+ZVWMlhhGH/zIgG515Q2Bcqr/gSBnqyjB2s4SMqUiK95qhPGCX5pD8/8BGcpWN/udrTVNgZtdcf0Tty8mN0amcpxf+Hy5BayBAAjMjCcVwvxxf32CPy52Y2H93OQQDkjCBA==,iv:KpYP8aTCFEZ5rg05OgeaFfEH8hiY4djNQRhSwJKMY/4=,tag:jni+bZ9O+1kb6SMzIepy3g==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
        SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
        ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
        SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
        n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T16:03:13Z"
  mac: ENC[AES256_GCM,data:ngDmvMuOWGMAf23hJsXcMZ5vXJuIJgOZSiK1WK3NVH1IVgbTmpi9uT3C20Sb4VpiZ9MAj8fgMcmdebob2oIuMm5o/K6rtiQzpmZvsBRNb2PBUfLdcb/b2COVwRw07P0piBGSdEYWeCt7ruWbn34+NQDMIldmXuDOS1ie2O3ax4c=,iv:2f89THGI50jm+GIlcUfy/tr2EDHn4Bu9wUx0ep2Ljqs=,tag:HtPzJdKesFPLre8pqq53wA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
