---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: authentik-postgres
  namespace: authentik
spec:
  # https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql/versions?filters%5Bversion_type%5D=tagged
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie@sha256:006b7801eacd9706d6fb557520a414a7d938e4e71333da98695f6f03b20e4cee
  bootstrap:
    initdb:
      database: authentik
      owner: authentik
      secret:
        name: authentik-postgres-secret
  storage:
    size: 10Gi
    storageClass: freenas-api-iscsi
