apiVersion: v1
kind: Secret
metadata:
  name: authentik-app-secret
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:P7lPxBXhWv8pepeH5kIE7qaiZYZ6ICi2MJAYy/VU9PF60RWbtBdw9ECrialpRE0T8/4=,iv:o9hUIeu7nz1/LOng2Ef27Kl5EeaCvkAesnBZB7Ji++8=,tag:bDa5fhyNFaT+gxt75/CBug==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RlpZU1U5NVA5U3BUL0pJ
        WnltRTJQTjBJSUtLM2s0amxkYlZKQk82NUM4CmltYjJ5RUt5Q3ZkTVZsNytjTG9U
        dUN1QlU5a1R0T2FCeHo5UVNWNm5UbmcKLS0tIEhLejJpNkVvU0VYaTBxUGFvQm1Q
        WXJlRGxpbk1Sb2lQUzBqRTNMMnFTekkKxGxe0T8VBzNYjA2AG1eWKe0c9831T1c1
        Jd8Cy5HyZwUMUSTg90gfuE6YKLOcuGTJncrluOw/s+/c34X4Tl42mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T23:14:35Z"
  mac: ENC[AES256_GCM,data:oP+NzlXVUbLIeaL8MFKuiCZtiSLh1R/3uATbNk09HsKMlPNzq52oxLSB0VNToDKziVaYW64kQ7k+Dv8judPbXYdtzafiNAC18SsEQ4S6bG4Q0zu4QdSB6SECtwCZ/m62giUYILcVgaR+3dXUXs4DrHIu0OVxglj58YvBHTN9u7A=,iv:JirEk/XCnuJBThNKRYG3QErAZrcDrpt4P01Ripj+K84=,tag:fSVsrkzw9EJ2HadayIztjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-db-secret
stringData:
  database: ENC[AES256_GCM,data:DsLAXa+Jqaap,iv:rEafOoU1eOwH6D8QmdTBURGmsb1UryQIekQAyZTwF6M=,tag:C0RB/IXmtcr4b5aiYXWlDQ==,type:str]
  host: ENC[AES256_GCM,data:BvmwrKmF0B/OSSTMghAkJiyACZx3,iv:fLjyBROReIaHv6vZoburMvQhK2av8VjZa6KNHgEntY8=,tag:SdlZ0B8K0uIY4MNImGVQqQ==,type:str]
  password: ENC[AES256_GCM,data:vFHhkOs3CVyYYZrR4+ICf3gFPM2Z05Q4OX65uld83qSbppnIVdaU6NSgv+RKvgCFlg==,iv:X2WD7y7EGaMHpSHZV6j+OMKZGnFPi1nOSvDCFTYlsQ4=,tag:jmO1qC5wk6XlZMsTpSqVxQ==,type:str]
  port: ENC[AES256_GCM,data:1D+DhQ==,iv:MwQPXoejP4RP4mmFDukIqQxEQWEGGHv1qpygd7dKIP4=,tag:Qf+Hku/TXkha4gMdtIB8eA==,type:str]
  username: ENC[AES256_GCM,data:gmwu6urGfzYg,iv:wZ5jwFNyjg0ySJFwDPdrW98TCqWs/bv0/2PnQIAYalg=,tag:tG7cJCI20LAT0oFwDod6bg==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RlpZU1U5NVA5U3BUL0pJ
        WnltRTJQTjBJSUtLM2s0amxkYlZKQk82NUM4CmltYjJ5RUt5Q3ZkTVZsNytjTG9U
        dUN1QlU5a1R0T2FCeHo5UVNWNm5UbmcKLS0tIEhLejJpNkVvU0VYaTBxUGFvQm1Q
        WXJlRGxpbk1Sb2lQUzBqRTNMMnFTekkKxGxe0T8VBzNYjA2AG1eWKe0c9831T1c1
        Jd8Cy5HyZwUMUSTg90gfuE6YKLOcuGTJncrluOw/s+/c34X4Tl42mw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T23:14:35Z"
  mac: ENC[AES256_GCM,data:oP+NzlXVUbLIeaL8MFKuiCZtiSLh1R/3uATbNk09HsKMlPNzq52oxLSB0VNToDKziVaYW64kQ7k+Dv8judPbXYdtzafiNAC18SsEQ4S6bG4Q0zu4QdSB6SECtwCZ/m62giUYILcVgaR+3dXUXs4DrHIu0OVxglj58YvBHTN9u7A=,iv:JirEk/XCnuJBThNKRYG3QErAZrcDrpt4P01Ripj+K84=,tag:fSVsrkzw9EJ2HadayIztjg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
