apiVersion: v1
kind: Secret
metadata:
  name: authentik-secret
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:sR98SmuFQ0SOo7B3+vQdzTqKoieA/37t87zlRDjiwn+HBP3oAQumc7Rq9X3SmXlwbj0=,iv:ulUJ/U0yo3LzbVErkUgdvFOvsWoTEvN+VNN4NqaQ1Js=,tag:gtK2oLr33QnYA5I55lJhuQ==,type:str]
  AUTHENTIK_POSTGRESQL__HOST: ENC[AES256_GCM,data:InLeA700XP7dnQgnuZYoWZzlFiaX,iv:2bl3pxJVGGCOeYBr0ESOPXZMvD+4SS7W0olBNPyB+Hc=,tag:RJ+Bt45SoOlJYPmFeEwOQw==,type:str]
  AUTHENTIK_POSTGRESQL__NAME: ENC[AES256_GCM,data:aHLZCqi6I7QR,iv:En8zRq8UHsSiezxQjTxUyo2jKRbDhT+B3uJmfUxlIT8=,tag:bDOPlVqyMal5TOfhm+gd1w==,type:str]
  AUTHENTIK_POSTGRESQL__PASSWORD: ENC[AES256_GCM,data:LVIZ1LkSoHZZ/oyMvUNCy96cUqEWYgwMsnRDLgJh/rOED0YJ8M6O9KY6MKR/D3mTDw==,iv:LoeYbZaQpbby4RYk4PRIBblKugoHn8uJ15QPW4/rfS0=,tag:snK/JnBUNvIaTvuJg53LuA==,type:str]
  AUTHENTIK_POSTGRESQL__PORT: ENC[AES256_GCM,data:prNLrA==,iv:uf4KuuMANGE+0fruycTYQ5N2Gyo3uS6m0f7SRMj+YBw=,tag:Fq7ivURZkLMbYKF0k9tH2w==,type:int]
  AUTHENTIK_POSTGRESQL__USER: ENC[AES256_GCM,data:nkViDm3KX9hG,iv:NvTZh5dQgYgHuth8SabmaSr4Pbk0n+8iO1STuGxH1Gk=,tag:qtV/A2fvmKpuTMejGsHSpA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxazNoV2VzQkZyU1AyVGJr
        bVJXczRLM3R5TjdUMTVvTVFzZHltbnVPWUY0ClYycWpsV0NBd215OEN6b0orMnhF
        Y2FmSHRYS3lsald5SVlVTFhNUmdlR2MKLS0tIDliQ1dENHppUGZtZGkvSUxXcVlV
        Uzg2VlI0REZ2dTdzdEpSTHY0OFZjTWcKLj1YNj7AYwJbP7xhofP4G88KTVLZE0LX
        f49p9tXmSeMxnWf+YiJHLfw3qIgyThxy3gjPwKGW56cDnu4pvzpUyQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T22:07:44Z"
  mac: ENC[AES256_GCM,data:Yie9jd+FLepGLYnQhqRP5NW/lCdTh0JH7wfxSuUEn0utabr66NGAoP19Et/cnsZk//TTADsoGLCJNVtlZlejuVTVVIzqMwd2XO9CREo4Ede57PHBJHZT1FmZdPiqr8Sp88auujbgD4mpiNzpEUeykMcn4ZZk0CGPrEMuSJaJg2Y=,iv:ZajF++I5OaOum471jOWlz/1vkg+okbgRiKtYr1WD7Nc=,tag:Q8/ieFoypDa5HYWvtqPnBA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
