apiVersion: v1
kind: Secret
metadata:
  name: authentik-app-secret
stringData:
  AUTHENTIK_SECRET_KEY: ENC[AES256_GCM,data:dhKkVjKDiCEZOw12qxRxALolXedp3jtuKlL0R42RuB7gjjvdni2AEG7jcEQ9xxUUpUw=,iv:qu6VeWUdzTdMfM8A+PDkY5/JjnAhYlwaYdqWvxE+BxM=,tag:l2ruzgAFlus2zBi5c4gO/w==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUnZWK0xaYkRQWUVXU09T
        Vnk3ai9NRnVoazJtRlVCY2NscnhsQld2aGc0CmgvVnk4Y2tEVklGS2diUHZpZEhS
        Y2xJTzdEMUlHYXFaQVhZWDBXVmNudXcKLS0tIENSWVloeW04cERKREtTTzQvWldn
        c3h0eHBWck9JRDd6RmtFbThZVzJoZzQKTUK8Xf029uJADjhr5DTUrphYVKoqAabh
        vCvJOyJQYWG2kkqjG4k6ex1/ISPsjm8DBkDl7oGgCIsmsL0vK9tBFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T22:49:00Z"
  mac: ENC[AES256_GCM,data:ObvT556J27jSyzDC8UvtQq4cgSR+ZMiWYVOZesBxe04506goiTXWaUv0T7yw7dZfd6m6k3Y4aeLFj2k9x3K58HJ/G+j8xSWCM2hVMOHdiDf+Pe3VXwYb7AZEZGI2LGtaTqoJZGkQeXE4Qz1YTSl52KleHRE3lzKKJ5ufwpBiS/4=,iv:S9YrRlt2zUOmsTyo0BtYdNfY29W3XmZvJJ8L7HV04C0=,tag:5z+OdFeiQ+D3X8VqpYupVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: authentik-db-secret
stringData:
  database: ENC[AES256_GCM,data:bhShGN0x6agr,iv:tZBsKA47IdxMopfA4dRi5JGqhw7jMOkZMnUzVbl/JSg=,tag:5qj6hUODkO8uzir3ReZl6A==,type:str]
  host: ENC[AES256_GCM,data:VHq9D/PVEtwg36TpbSwPtRe+2eTI,iv:mvZxHva19m1M23X1cubaTkFf3Wyls6BkNJk01MA3zIg=,tag:9zqbnBo/a+QJctdiz4CD3w==,type:str]
  password: ENC[AES256_GCM,data:+mIqu7bl2XhZLxilHtLXroAMr0VgXDYqDzSGzofxXZ/uPjXnsx9Q2UqC0w/YYrYQeg==,iv:tnJizuRzFvq4s45CFFVD4k8W3Q6EXrANfxKIFeCLNz4=,tag:asRTzcFyW5xImDRqVGvGIg==,type:str]
  port: ENC[AES256_GCM,data:BNy2tg==,iv:369zR3RnpAo7TwhKKjZOb0RcZocv+nbDiY2yQyBjLsk=,tag:iIzD8z1XZomFWK2tO9++2g==,type:int]
  username: ENC[AES256_GCM,data:E0NFD03esR8H,iv:i+d0WnyOINeBluRae5awsAIPKZVrRCG04a+QM+oh9po=,tag:oqSjFZl+JtgUjLHAJE/7DQ==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUnZWK0xaYkRQWUVXU09T
        Vnk3ai9NRnVoazJtRlVCY2NscnhsQld2aGc0CmgvVnk4Y2tEVklGS2diUHZpZEhS
        Y2xJTzdEMUlHYXFaQVhZWDBXVmNudXcKLS0tIENSWVloeW04cERKREtTTzQvWldn
        c3h0eHBWck9JRDd6RmtFbThZVzJoZzQKTUK8Xf029uJADjhr5DTUrphYVKoqAabh
        vCvJOyJQYWG2kkqjG4k6ex1/ISPsjm8DBkDl7oGgCIsmsL0vK9tBFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-03T22:49:00Z"
  mac: ENC[AES256_GCM,data:ObvT556J27jSyzDC8UvtQq4cgSR+ZMiWYVOZesBxe04506goiTXWaUv0T7yw7dZfd6m6k3Y4aeLFj2k9x3K58HJ/G+j8xSWCM2hVMOHdiDf+Pe3VXwYb7AZEZGI2LGtaTqoJZGkQeXE4Qz1YTSl52KleHRE3lzKKJ5ufwpBiS/4=,iv:S9YrRlt2zUOmsTyo0BtYdNfY29W3XmZvJJ8L7HV04C0=,tag:5z+OdFeiQ+D3X8VqpYupVQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
