apiVersion: v1
kind: Secret
metadata:
  name: prowlarr-secret
stringData:
  PROWLARR__AUTH__APIKEY: ENC[AES256_GCM,data:H7B58IhQ/CQ3DUgZtmqfnVPlZ/IWDtV2L4FuhfbQIFLhEp8jPtsW6jLEJvt+77kBqmLlpWcgfdn02ypy/vX7Lw==,iv:H4P3y+1OGgDnwMWLXFV59WD/cr3XRJsbCAIo61cm9lQ=,tag:3mm5Pw7U6wv4f+k1sVgwqQ==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAybFBidGZLTytJV1A3NUtS
        MlVZSFZXWmVzTUtVRzFPWGJpVGNtaUhrY2pvCkxpOU5DZUNHcER0c1B2elZEMUNx
        aTUvQXdmYTNMNzFvTGZ3MjBSQzAxNTQKLS0tIHNEKzNIdlN6OEtHeDU1c1RSTDhO
        WXEyQ2RTcGYzcW1kQVF1LytHQzhtZ0UK3wFdJ4NPHdvxzn5KHjRrTeMxcm7Vj2zh
        y3AiRQaxoeBoRQbm3OYh4mXtBXuRpo+hM6lznlNovU7JN2P6qmuLXA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-04T17:34:30Z"
  mac: ENC[AES256_GCM,data:2V/WN9EBy80qam7MpDzQd+0dUs5xkLWofmIGaZ7uOC73NdPHToNpjR9I2hr4aUzgminzovQKxRQMbAgBWUcXN/bjvtrmq0gPtiaxzQq0/joCwN+YTXnaeZz7oOREOzryC07sZiCzKSqzXiuExOMzOZ63MgcabWKC++IYB19HMsM=,iv:hUZK2aEjInZ70VBaDVNMhjjxBeMNIReivMO8Z1QMMZE=,tag:ftB9yQa7d6gsrkCb574ISg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
