apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:NCURdveXBkatccFsaWI/eHDF5zCUznMykIdaSpGBi4MrZewqZWZyhLuLJuVj5C/R/lPZoIc=,iv:dz+bArVg9+2DA+PwrnZSnwMzoA7VP66rG8kDwIFPdN4=,tag:AZ45nqgNf/6yo549gpxW1w==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJU0tPZTFVaVpxRkk0TWRw
        STVXUC9aOHZITG9YcGFZM01mZW43aXhwdGdrCjZBbHJ1U1E5dWY4bUpYd0FBNVFH
        eTRTb0FCQzN1RVVBdEtzQWhpLzZleVEKLS0tIHlQTW10TFNpelZjSVlPbFFSTSta
        b28wZGRGL1FkMHF4bE5keW1aMXMvQkUKEs+HhDzHrcrI3t+a/UDcfQBA1ciF9vmI
        xeciE3/U3Q70JIha34mvLIKnDCQJ3KTyqniRdOgkcSAwjzaL4H5Dkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:55:34Z"
  mac: ENC[AES256_GCM,data:6BEyofwtU6QTodEbYp37HWSByalRr2/bqA3Ye3uQYENyA/TQBgh6w/4kwH71SPOL3+hIHxwQ2giaQWDiUszX7VJR2CasQK9ub+8muCeEc+PEtFCrV4T7qzCFdeP1NKbD3xAMfULEamB+bwMHp4QKTVJz13VL/XMQfSBGrIo3QYM=,iv:fEWXCkX827HuDeU8wJbt4S+CFN1owFfW4Cj0vc95140=,tag:AQx9FU/+SoqD1dzon8A7nQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
