apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:XV7oSi8Tw2Qe32fk,iv:CoO991a7qq0cgseoyjMsU6hMjmE1x1RTwF63UUkV1xA=,tag:HbAR305t/KVM6bPxrKVdmg==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBleUxTdFdTY3huWjFnYkYv
        ai82ZzlTYXVZK1hQVHJYNEpLRHJHYUVNbGg4CkdYVDJNZzcydHJPeUdyMWNZTktz
        cVVVNWlmSVhjSXgycWhONG1YZk9kNmsKLS0tIHRRb1Y1K2ZnbXFlSURYTzdva3lz
        NVcxT003bVJ1RlBOTTA4ZGpKYkdLVU0Ksj9BViPesVCw/VMfgvi3v9RVQg4FmNql
        LUnN6fqLgFAIHeFXjy9ngoTFzMiWmAogYmgq53R0TAazj2BLL4+rkg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:55:35Z"
  mac: ENC[AES256_GCM,data:RAkQyHokz1dd/Wo6FZmlNOwDo31G+yyfuj/6YMFs+1Azkln56r5rb5RisAG2PFCL/6klfhjpZnL5Gx6GzCprSc854CKZ0cqBjHJE4paGqwTkSqZei0vHJgq2OuhFS+lkGZ6dGpG8dVs4+4pUSlSf7OKxLN6sArvU0Muy6g619Ag=,iv:sezKHNw+BdrIqMcvn/GrYM4vpuSq2gu1RUTGpRsiWHY=,tag:nli1wkmNYNFQeDjhTYgIpQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
