apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  INTERNAL_DOMAIN: ENC[AES256_GCM,data:drXTaglVTWRncxk=,iv:Xt9elp+HCN7CDrqCxzrFnh88ZdjJ1r5golf5gD4hehs=,tag:S6wTt2Hn3pUNQ3Lxt+xgMA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:9fGa5oxbWOm0vbHl,iv:gBWV9Jio29jvrRvPaaHH/dxs2/ryDBVkabt773Cge8I=,tag:/fbBZCZzjmkdwsFv/g/DHA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBraUt5eGtaaXZhd2JhR0pI
        a3g2VnRzNVFscWlTMlo5bkhVV3FJUTJ0b2dRCllSWWtBTnlQcUNac3ZJNEEwUzNQ
        bnJZR3VkTGZSMFZ6UHJWMVM3NEU3WmcKLS0tIERYNGZaR2xreTc5ZWZZUW5SR1Rv
        b1lMVU56T25XN3l1TG5ES1RXTEpUKzQKAoNoobys+9O3vRaiLR+gw7aw2S8b1GlC
        hY61Yjy6h+RetMAZtm6uIMIExRjOzSOiBV+L/L1G3fVfxLA2aUA9yg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-05-02T00:08:56Z"
  mac: ENC[AES256_GCM,data:ShDzKg7+M4CGQ3vyFMES7QR8e+EwDrD9QC8wp8Tz2YcgkDrrb+hP42HLykc5sHzcgqsHFA7SPs2r1R4Ro2r9L6o+Ulm7+iT4EAEJa2VsjYR5pJgZf2nNLXx8D8me+bwhtNpENuj1HVYZ/6NFvlUwHUFsOznG8mmKn1bqaDkQoIU=,iv:PfgFlJIMB0MsQwyavGPVrHPhXL9kmeEwJMZeL+s5u40=,tag:QRvtcL94gy2RvncAz8pq7w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
