apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  INTERNAL_DOMAIN: ENC[AES256_GCM,data:UBcdej6o4FTvIVU=,iv:Q1sA30Y1RghVMw2YLT8s5HW5P6ZrdOqP4YUyUTj9kFQ=,tag:IpT1dkkiZXy/3oHytPT+tA==,type:str]
  SECRET_DOMAIN: ENC[AES256_GCM,data:33we168u7/bcgx7B,iv:dFO4n5e0opWXv3ekSqcUIClODvK34Eavj5CpGKi5U/8=,tag:KN76FHKtyrDUsxmZsIPENA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwMkJHalV1cUw2WFhsbS9y
        YjBNT2tFaHdqQW0vK3FjN0RqbG9OZGlUUEdjCnNFZlNOZ2hERVFOOFM1RFlBMi8z
        K0NNZ2VJU1dXSkNSR20veXJRdWxPbjQKLS0tIGVEdkY3K2c1TE1wVFo4Sm91K0lI
        SWZEZEU4L042UVFGSkRGWTkrdElKcW8KRTxhWgQcxAg4mVVmMszUohXfc8aoC1tL
        3LiJlQU5yb4UgShn7oBIXjNPqnYX0HYIjssjuEnr1/g9tTFXVEdzaQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T19:11:29Z"
  mac: ENC[AES256_GCM,data:bOD0nlIMZzcUdAqgsDOHIGF46EkGa0P0G50R/awkm9fTGbWYId1VZaUZZevaehVHWymd7eYG46apJQcsvv/XVgwBysk07j7gBz/p1qf+assUD32/p8jcbK2fIHVra8TweNadKcvY+lvu/2muL2Hn0P6DJpkZSlQ7hyAChM+KIrM=,iv:uVXiPwDGF3IV64yFL1dKJCJ1F8wpZXUdSCUk3f3XVMc=,tag:clcNcKP/a6e68cHPtK4P4A==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
