apiVersion: v1
kind: Secret
metadata:
  name: rustfs-secrets
stringData:
  RUSTFS_ACCESS_KEY_ID: ENC[AES256_GCM,data:rgwKgsKtrRlr9WiTx4K4kfDszdI=,iv:4xOx9SsxIwqdxVWVkJtJ9BSQmlryNXn9F26JOScDKAA=,tag:MZqch6z9h8d5TiXFkibI0w==,type:str]
  RUSTFS_ACCESS_SECRET_KEY: ENC[AES256_GCM,data:c7Tty0cyyTvdCHVwH6jP8nC9VJhDLPxFuFmVIql2yPUFZSS+C/6A8Q==,iv:nnrl9THv4Th0snMcjbrslMGcmi9h7yYr/fHOV7cNgTE=,tag:YWAsU6p5xA4BfRmcInFJ/A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSSEd5N3dxTUtROTdKMnAx
        eGxwdllpN1pGR2o5a0hMUGhpYVFmM011ODBnClI4VlpZTUNLREVvU2pKdGtIREZX
        RmZjNW56b2U1ZU5ML0FSVUhWQlQvNUkKLS0tIGpPYzJBSVNjR1JDcEpYRWVORTZX
        KzFJamNlV1JtcEdXM2MyQW9MN09xcWsK2Wo8LfYGdqmnLe4NVkO0JRnDxIInFnU1
        64DajETxtN5h3A/7ETR9d/c3n5RkvvLVO0Jq4IUwpYSHY+GzVTFArQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-26T19:12:47Z"
  mac: ENC[AES256_GCM,data:Ecm36XVkwXhzWa42qrhhjCkvtbtPctK2ktUs/tRzGP5EBHhfk30EnIWiZ9g8PGPBIXfweUdYS+VAyuIdvZBMDDukbnd5+DaQKLjK/xmECHoaVx5D909IxhV/zztu2WKfqgLYuTNRvU6Q+gh5yhdioLXyijgR/TpwQI+7WQn/EMs=,iv:+xusDP9rLCALSJdclRzI7JW5O/dMp9CaF2ezGnYokgI=,tag:JjwjjOf6BgFWxz7dimb0LQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
