---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: freenas-api-iscsi-sqlite
spec:
  chartRef:
    kind: OCIRepository
    name: freenas-api-iscsi-sqlite
  interval: 1h
  values:
    csiDriver:
      name: freenas-api-iscsi-sqlite
    controller:
      driver:
        image:
          registry: ghcr.io/democratic-csi/democratic-csi
          tag: v1.9.5
    driver:
      existingConfigSecret: freenas-api-iscsi-sqlite-driver-config
      config:
        driver: freenas-api-iscsi
    node:
      driver:
        extraEnv:
          - name: ISCSIADM_HOST_STRATEGY
            value: nsenter
          - name: ISCSIADM_HOST_PATH
            value: /usr/local/sbin/iscsiadm
        iscsiDirHostPath: /var/iscsi
        iscsiDirHostPathType: ''
      hostPID: true
    storageClasses:
      - name: freenas-api-iscsi-sqlite
        allowVolumeExpansion: true
        defaultClass: false
        mountOptions:
          - noatime
        parameters:
          fsType: xfs
          detachedVolumesFromSnapshots: 'false'
        reclaimPolicy: Retain
        volumeBindingMode: Immediate
    volumeSnapshotClasses:
      - name: freenas-api-iscsi-sqlite
        parameters:
          detachedSnapshots: 'true'
