apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-sqlite-driver-config
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:XrtYQKvOmU+/XD+UaTZ0L0lGmG2ZRb+XzJISq1gbfqDSDF7em1zFSUxSKI35j0kcN5wQRYnYNiFiC4ZlGeSWhQDy1P26MdgZNABIxbOXZBcpCwVpGyqNtGtP6O3nLIocD5R89AF1eVt0ja5nXMiol+8zkX2sAztm6v9yHOAe93AlYFyY9RBZSpLknR5AUufFF5V6FD5li7VnjRqHttxnT0EE3cOeuLOLv5+/7y8UXjQhAVegC1kWXmvcBqmMz/KgMDSo/Wim6OjiQBpTdQJFtT/1IS5O3/yWZnZOMt+Xe3AkH/MQAZACvaNcvU7h6R00Mk4TtN21ILlK3P2XqHoLTd2FkIZERfNcLgO8xtIvajVOqgllx0Dmp5c2k2pEDZpL7A3u0e3Hd+14J93uXKFOKM0WSKLl60PHwZZQ26n2SLau/4UPz5iyveP797IQokAXRmF+gvAHa5yIjHEwP6LSTQ0FoyCMZrtCt20gePKJ6mEZ0e+31zTCVi9CmmUWbthK8wt7J+6FpcCiV7IeqwseMG1YMsP4Qrgmwkan1CFIatNGVigwWMJNSSLoVKwv8OwMyLs7ZqgoqTL+Z+72rEsmPm9Iti0O8MFjZ8WQHup8FyeqYvcsfTt4hc9ZZ2rpQhJR3t8pNzL9P7WAuClm+R2Z+SoHg5FkwXXCrO8vuLw7AVuZXYU0rx8JqrYMEUb9iDa+nyQNPzjfpie7RaOJ868JZfaJG0o6SXiAmIq3fco1/goBT4ynefEeUtEx3vTXSJxAEAAZ76bx03RfqDQRVPzw4bTfHMKuFmVL1aceVOeWHAAWCG4DOba1m1hfWox91Skcx9EoW6HBhqBeXMzYB6sDURUb4u7CX6ljiCjbqpfdqtrfRm7fM+NTeGFi/pGxrBcxVRJPWz3FHdQFPDzOHkSvC4GzpplJbzcv88iWZZgppApWXRGVw3nf0pNifh506qZOOF4+hsj87zLx+QntZK0oIa9x+jU/friFvBKvpy1Y2AKuYF73uEr3q0Q+YW2EGHrk+M8ZP9x5wa8CCtprK9gdpTvxB4FkkyH6CDtDsKSYhzH4T7BlnWq3gbWCVhc1U2ygwyVQN+HuqQoCQzAqj87i3WdrNBBoK3cdnzSElNowoR2ZhQNJaevKLniIrcu95b7o5GIuVBbRIs+cMqMJOq5BVxQWK1dxoIgdUHMQbuyh2IM+xOpEyi5KbUe3o3Fc1C6+frC3VTc2m7eBD6bU3iwh2BWavPNK3R9NvPIwcxwVY0+l35BVSBgHbUn7b64SMKOb802nL5tCVzwbKQTCWblpQnFUvVW6iUA4rwNE4BvNxo9MBt+7tx5ejx9xHWb+RnvllrBAtXgLG7k=,iv:E+HzSL1VGye9tTxkPD0/DYJc9UxuRbWHwRG/SPg8/ZA=,tag:sMA21mMr1L2xDTabK5Dcrw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
            SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
            ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
            SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
            n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T19:21:56Z"
    mac: ENC[AES256_GCM,data:16ao/SkKhJBuLF5BtN+yB6jIzd7+TVyyrLJxCel1cDBuvvxapPKJ83Isu5rcioBw4RNIUT8aXOcKpNBcttyDEZsa9u3miMoX1qQFXEnaaAcvt49ZX09K9u5wFrz7IxmISZ7gpWNWCGteTt3GfMZ8yuJ99849uaoNWS17ck2L4Jg=,iv:9pvHc7wHRsT4oz30y86sxtaMVDiRpOb3YYaG8knWmSA=,tag:aIbehWBes75AV3AF+IEIVA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
