apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-sqlite-driver-config
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:uZvw3q2kqnWkUMj5+zfsxwchkxKGw4gt7ECK6O7gK7yDtD8nc6spTx/07EUS0mPNzc1ILb5/u0DSUC5pyYcSvOOrHEdaRX4eMlottR8nqvQtOQG7XjdxOdzDTsFCmQkn8mvRNnGkrEMM+ZiKfCyMyljrla3NaEEXeKtCbTe71Ruty3pzxI0yhF2kztya5b/H2DsH9zDaRpJX9Wyg52ivXGgH5g7f4dh5yamO8K/F1QUZrl6s6VAsYkcxJ+O/hfZvuqDQa4GtBh63Id3km7nR7YvWTtrDxWBWgxtKwejbokNmDGFL6eHoB55mcEVFi8llWjma6wNThM6Kx+kYOsvOtfwUcEgQUrl1ONzS0jVAEF+ccpCLDyjFzpOc6mcSInLpSOrbvrkaUNaPZdD85Dq9R0oJOTt7olCOMIOS6/SMevTv3v8kNAYv1Wfg2U6dgWQd83RWVGr2kyU8Yol/UEkycV2qPoqdNXJq16uSbhbh9Sh5DmEgBODKXHq1BCvPE9oFyqxfgphqzZUKfWYVhzUX6fNvQjinwca6EoyJhoUvJvVTsN8vhZCHA/gCZ+OYG+4/pIaAWvPVPTb6E9wJGs/jglaAKHcKO75aghcuwGcgWabSEbQHUryhONPj9muHelikqoWBeu/zePTJRAKFZoByeMcyAUJG3enTSeoV4uVFJblcvmO+wStKiZm40eMzqwM/2rIj88Mi2YnjwjbgsMr/fUQ6rCbX2Mmo0AburZ8QelhoYTXd0y9Z5mBUFdgj5KFTSu74vQRZOmwCuN4akhqpzBVZAGFvYfsl66c5k5YSIQT2ihv78Jb46fv/PMp9aIbPGJv9mRX8aKahJhXMxdYewamxfVAg3MD64HX9mlETHMHudEQgY+Pv1aRN83QDJ8aI7wJu0K3Yy1VOLQkowA0xYCwENyQ73ElsYFfZjnwkCVEtfowalQ2Ol+knwuxv3Uxs0qQ0dVFTlCLQIUaNpUQN6f0HZ1SL0+WCNYd/2YP4aFHigkXUseNoSFwh+729WbsYeLZ4UHxlafg+7f22ZcVbvBnKlM6Ia7RwFb6mCWssVPCbRg3RWi2EaRQo3EbLxFt98i7XatTSBtsSVSb9EwlwFBbOZW40pDh0RvOwo9LE3Gg8DUq3XwPfEyKcqo+Oaxpj4Jz+BfG5LIQyPxlL91LASJ2/lWPvyxaQDdpbuKkG559fA5vIzx4lUFSwINTgIz9O9UcAgaV9v/X8obGCN3p/1hc+nfQwx43iEJ/0bXDMbuUaKkgW4skRTFvakkoa1pRNQqxZc7VyNosZhbdcZz48sNdDshX++xJ4fFC0IMlaHDVoym+5RCHMUzQ+oFIrF2Q4kqytjMsD6OU=,iv:ukS5MiJFWdcl+I5djEkq+SApZ2Ab8oYXH6fEbUdQqzI=,tag:27L2ia7oXvV9WgOGY8XhCw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
            SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
            ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
            SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
            n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T00:52:22Z"
    mac: ENC[AES256_GCM,data:fawBxUqa5NCudKsUuoXiwz/lFIanzZOQiKEMsKKvnMl4XsCP4tpykVb5ERYYFfE9cTPqMRWKtp7QGcwfBzdbV0eIziPynhgZ6uSVz4cCSlPhm/Y/WVypnZr80EqXQJIRtt7tGEDKrwTI9fa8l/COG3fhGqLv+29h2I/Vcffyn5c=,iv:YT/Wp6XyyADNGxPEFlEvvsuSFnLcpat15f7k4YN7oTc=,tag:WlU9BukY38bloOC3/gN8HA==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
