apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:BqUzkAtxMVsHC6c6Ym+DiyhL+2ZnGdATtSfRARoH/H4=,iv:ez9unYezw9aw9zolTfHzERuE9VJKE6VLARsn2WSAxlM=,tag:R7ljblRiqCsxO8Jaso/ckA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVHM5dGUzQ0R3aDhpeC9K
        UUVUR0lFbUMwb29McTUxMnNITFF4Znh5bUhFCmFZMDJDaXR5elQyVWhqM2ZJRkZG
        ZkJEakUwdWxFM1hWSU0vdm5Pci95bUkKLS0tIDJyMTVJeXErK2xlbktQN2k4WGRj
        TG1HK2Y3U0pwVmJVai9kVTZSdUwvWkkKaLWrxHanYcGcj+HfUHnhhpwa6U01Tycj
        okZLSbXJAYXiKmVxltp/cBNQIxfshmsaxPKEo7P49PPWKDxI2UttFA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:55:34Z"
  mac: ENC[AES256_GCM,data:cG0WLBxq2s2dsdkAfre90PpnNbJ18AYwjLEBG2QiSOge4Z9LBMyjLuhJvjXpEsZsTBrP21MmJ64YeuDG6OzqzqVj1mKQRMb73a2VFMAaVkqcJw9wQFDaSEUj2sBZ0aV/hCLhNSFySHF3gyG/ZAYnqEYS1UMiutOr3rAHohsIFAQ=,iv:yLp+gBD62WNynBVgreuDOQ8Yz6IEs+3DjeJEaIsFVZ0=,tag:KQtUFu5neuAN/3IggOs0rg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
