---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: syncthing
spec:
  chartRef:
    kind: OCIRepository
    name: syncthing
  interval: 1h
  values:
    controllers:
      syncthing:
        containers:
          app:
            image:
              repository: ghcr.io/11notes/syncthing
              tag: 2.0.15@sha256:32c2e6f8e73006be5338a34d3d8fb84a3ac584ccd12a6a0d9f4852363e2b8244
            env:
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /rest/noauth/health
                    port: &port 8384
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
              seccompProfile: { type: RuntimeDefault }
            resources:
              requests:
                cpu: 10m
                memory: 150Mi
              limits:
                cpu: 2000m
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 2001 # media-rw
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 2019 # syncthing
        runAsNonRoot: true
        runAsUser: 2019 # syncthing
        # supplementalGroups: [2001]
    service:
      app:
        ports:
          http:
            port: *port
      sync:
        ports:
          sync-tcp:
            protocol: TCP
            port: &sync 22000
          sync-udp:
            protocol: UDP
            port: *sync
          discovery-udp:
            protocol: UDP
            port: &discovery 21027
    route:
      internal:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
      sync-tcp:
        kind: TCPRoute
        parentRefs:
          - name: envoy-syncthing
            namespace: network
            sectionName: syncthing-sync-tcp
        rules:
          - backendRefs:
              - identifier: sync
                port: *sync
      sync-udp:
        kind: UDPRoute
        parentRefs:
          - name: envoy-syncthing
            namespace: network
            sectionName: syncthing-sync-udp
        rules:
          - backendRefs:
              - identifier: sync
                port: *sync
      discovery-udp:
        kind: UDPRoute
        parentRefs:
          - name: envoy-syncthing
            namespace: network
            sectionName: syncthing-discovery-udp
        rules:
          - backendRefs:
              - identifier: sync
                port: *discovery
    persistence:
      syncthing-env:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: freenas-api-iscsi
        globalMounts:
          - path: /syncthing/etc
      syncthing-var:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: freenas-api-iscsi
        globalMounts:
          - path: /syncthing/var
      syncthing-share:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: freenas-api-iscsi
        globalMounts:
          - path: /syncthing/share
      media:
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}-media"
        globalMounts:
          - path: /downloads
            subPath: downloads/complete
          - path: /kyles_photos
            subPath: pictures/kyle-syncthing
          - path: /haleys_photos
            subPath: pictures/haley-syncthing
      backups-kyle:
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}-backups-kyle"
      tmp:
        type: emptyDir
