---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-media
spec:
  capacity:
    storage: 10Ti
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.0.10.50
    path: /mnt/storage/media

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: syncthing-backups-kyle
spec:
  capacity:
    storage: 500Gi
  accessModes: ["ReadWriteMany"]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  nfs:
    server: 10.0.10.50
    path: /mnt/storage/kyle/syncthing
