apiVersion: v1
kind: Secret
metadata:
  name: syncthing-secret
stringData:
  SYNCTHING_API_KEY: ENC[AES256_GCM,data:jqfnoIPfU8CnfFH04d2BJc9GBCvsIPUmx15kyiIphqY=,iv:yReNbS/vYePEZlxMA2M9OYjGlNgtry0nVHmQHPLrnrA=,tag:Hhg+OZTgu7Obbmltk3Qjig==,type:str]
  SYNCTHING_PASSWORD: ENC[AES256_GCM,data:6f48y4GUUqh7U5aH3x8M7VbCSORzFLrXZmCYCECm61M=,iv:64+j6+xJwNdWraxVVrFr/AW6eAVJ7up8NcWlRu1bkso=,tag:Ez3Ojd81kfekdAUKbCu5IQ==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVc0pLaVRZWmViMWk5NUsy
        bWhHSUFEblRKTHRBQStzbWRKVDlrejFaY2tjCmc0ZlFER3Q2ZzNTakRTV21DNi9R
        Vy9janNLdHZ2SDVacXZOWG9tc2VTeDQKLS0tIDFCR0YxWDRHNlpwSlgwOFgveXJN
        MEQ5TmJ3U0dxYmtDWUwxZGNIa0oraTQKN7k8a9Djqz0v0H3zi5yVQbxFbg0KRekY
        TxeHHLxsAk4ngnpiN4+A94UFyEwKmfZv+ksfkAjO3UGNPaYUU3pPjw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-07T03:05:27Z"
  mac: ENC[AES256_GCM,data:ZtIkWASs65gEJ5iU+RlEI/nF5z/Px52cucR7MeJOCqvQMQWtKI/VAvMnMbixzoHQRYvbY/zgAoQ38ATxA6V9OYO7RKigPs2XePSOgjIA4pXWf8N42UEp3hMgtyMIwwN+3k2wX+ZlU4bZH6GAQLh58ZUGnf7/SJdKS+b5fYNsSQE=,iv:6KAdTBVT7hxbbKvqZeDo5E5kojdyDl147OWjwFN6/iQ=,tag:WsJ+nl0ro3544v30g6ZlhQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
