---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lidarr-media
  namespace: lidarr
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Ti
  volumeName: lidarr-media
