apiVersion: v1
kind: Secret
metadata:
  name: lidarr-secret
stringData:
  LIDARR__AUTH__APIKEY: ENC[AES256_GCM,data:5A1rhCYKs5eh8xr9rTiafqVEjw0osbSMrHQ1OhgtPEE=,iv:dnYsWazVva7teTsCTtVJzOWsC9Ken2Ji/uX6BFR693o=,tag:RlM/N2lHccAZD+eYeF43Ww==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLdWM3WWloMXdmWkx0REN6
        UUNjOHRLSFFtdzg0M2VTa3k3VEZHbzdZNHpVCjFWVHgrY2M2RFpoNGJJZ2lmaEls
        UExyaXBvOTZpS2NnR2VrUldCa0N3UncKLS0tIDJWOWs2ZnVZaHNXRWxJTCtKejFr
        czc0cndqaWphNnpTZG5mK3BVRFFTemMK1sS4SdyTp4E2Tq6Dl5lcs3MPEEwV1Kif
        T7VomKXp/mo6xiNh2/U0bOqWrrrE2IBVDZrW0Xjzj8bw7hDafsPPrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-27T01:11:10Z"
  mac: ENC[AES256_GCM,data:sVLUr6Cl1QTthxyKQe81sqDA0uH4FKA1ngBDlOxm49VBp4DDZTQxxWK5zsGoR/BBZAftOL///2+lI4KMb4MXHeChFPdbeh30+or/Lv6P4srB2JChYFls/MYKb9dK+zaRgyemk+9cD5Q/yD4R0O9iH3FxHRM9HpiEiu715BiV6L8=,iv:hwP0I3XTeEh0t/esg2qp8wjdgqPd9QUNOZ5Evz1FD6Q=,tag:XkryJF7EnByZ7pUKHQjIEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
