---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: lubelogger-postgres
spec:
  # https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql/versions?filters%5Bversion_type%5D=tagged
  instances: 3
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie@sha256:47bd8dc5695a7f6f0189e205dfdb964aafbfafc337152c792ea62566edf75c33
  bootstrap:
    initdb:
      database: lubelogger
      owner: lubelogger
      secret:
        name: lubelogger-db-secret
  storage:
    size: 10Gi
    storageClass: freenas-api-iscsi
