apiVersion: v1
kind: Secret
metadata:
  name: lubelogger-db-secret
stringData:
  database: ENC[AES256_GCM,data:kOoocsmGYzzArw==,iv:8uHYwDVuTlVmK94FggcelqNvXGfbMtNzV2W5pkryLnM=,tag:2mhi2sLu4A7RTL3wn4MYLQ==,type:str]
  host: ENC[AES256_GCM,data:vSNTdCf2KiP7Qv4Qi8b+6xDkPBRiEA==,iv:uy2hAwPKqjsMXE0cAXDfKY3jGg3iJ+usLvpdPRM4xN8=,tag:lpK1V5cDpwCeFqfYPFSMwA==,type:str]
  password: ENC[AES256_GCM,data:1OYRQ7nZGofNRwJYstI6ooXGP8wWQwpKAPCEP0S3RumyS8TKnr3uXZ0Kj+dEbACCCg==,iv:xDoXsUvMp8cXq18hR+HGGLWW6B/8j8IXq4ZTF//mz4U=,tag:IU/KxVPwMJf0UrbotRTGNA==,type:str]
  port: ENC[AES256_GCM,data:opsncQ==,iv:FgFJg3HAy03IwN4NrLFCRPzyr4a4lq5YBjJKUPPIcHY=,tag:5z4EC2oZDrIDpow3VqrJYw==,type:str]
  username: ENC[AES256_GCM,data:7ytO3h66lG96wQ==,iv:HKeXBxLdxNT5jlVDVxjRsi9issiFJKQRw1VTUkbD1JY=,tag:UuqWUE1wJwpLHedU9ERDoA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYdHJEb0VjRWlBbFZkbTRT
        VlNEbnVCQlZaN0wxK0lBdzMrUmYrY0VwMHprCmxxNEFpeGVKZkx5TWVESHVCUVB1
        aUxoVzA2V1YrUnljWW9ja01HQkxKZUEKLS0tIE8zeU1EUFRzMlUvMkpRSDdCckVa
        ME5jeTZpTjNRakNVbjR2MDNIc09VNWcK1DftQJcrJFD8kZ/NvUckBtG3tC0Lmnyo
        CcYmxXZrInIJxtWmvc6Fi0ErVHfgzU21xyv0dYZj6oyQLYHX3ZBHmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-18T02:08:47Z"
  mac: ENC[AES256_GCM,data:9qeTvUUXPjInNQKOIf7f9DaaU1v6o+ZYq8d2fJaeucX23IV1YSZxngr7aW3AvlCeGgnT/a8OABjHFHVHG7MlpjkcvYbxB096XRI/G6jSt+f/6yqXc21QypQsgDi4uFUvgx0sBZPAoNPyFXJPuvk/J5EUie7WQcAqjsUbVpUS33Q=,iv:Ygf+mEaVVjolCJmXxb8WuFaB1RaNZENpKKPLBURjc1k=,tag:3ELKf2OwQcHV34m7NkmwNQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
