apiVersion: v1
kind: Secret
metadata:
  name: chaski-secret
stringData:
  NTFY_URL: ENC[AES256_GCM,data:xvPtJIYPcTVnDNochyjZAaKeMf2fI2uYphMo4dj8OkFG+gbkzPkyfDC9dGh/lR5MxNwQUdYYULKkf1JLgZI=,iv:XHxavIPpuY/SSwLJ28E/dIHbBxSOVwyNxYn9edca/5g=,tag:ElcvISXeuafGkz9qnEtQ8Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2SVdkSEM0TUsxMXgxVG5n
        UmpsUitPL3Y5VWlYSUFxSXN5ajVTWHBsblZvCkszWlJXVjA4SGpuT0ozeUswZnlO
        M1pEdzRKTXQzWG5PejNUQXlENTNEWE0KLS0tIE1OWCtRRE51NkFYVU5vZ2Rzc1o2
        WnJLclRMSHlWOHBGT0l4WXpON09mU28KXtgYSdd2wbz3AxvzsoavA7J41bIBD610
        /u9sjhmnWqIIQx+rmNqLpKv9mKbw/IvNsXhfQHipCPh0A7FBxbWBhQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-13T02:16:42Z"
  mac: ENC[AES256_GCM,data:1RzREqltZJGFKQNHEC2JzzTywQihtFTiSLGTpOfgOwO0vAPRHdwS5ItUzfQq1vJdRYPAbJ3vDb5dzHtKwwiRp+dXO2zIVEmOzR6e0Zt8rw3EQkHu2nLZ7J3g+ux2Ru2MhK+SrGCiMmI/Qrgg3UqzVu/KYvj7e0EsnJxhuvtMshE=,iv:NQJnO9Lf/R489WgPquWhmjytIhvl+9W74+uy4aEeslg=,tag:QOiRQtLYY+fjLTDPDXlY6w==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
