apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:lX+n51iayhau/ldYsJjhhNzTBhAm4begOmdGAGwJ0Yq2NdUWEOVQkzboxIsGyq8Zl5fEoldo9J5uOdf0bNKApHq1bMkCijQYAulQQtGLtFLQta4Kto3JS7GQGdW/3amgOTZzpinh8tC1FBUgr/9phPi20S4G9tk8uEpX9V3uwHWJexfMCALU7IYgXgA4WlMynXYcN/fDI25pzH3SitM/tKTkLP0FLcvkR+9SwTgf2HNhKu5W,iv:r1YS/N6G2G2XTA+sLL+3HTaNaX6S5Avw2JN4TtdUoXM=,tag:tkgp3FL+HMMQR2dZ+s3ytw==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoZmxXQU9QTGRVMFNVQ3RO
        d3h3MHp2TmYxOGwvVzJpRVRQOXdsbStueWlVCkVHVXVnZXc0OXQ4MWpXYUplenF5
        OVdnMHA5M3ppVC9nb0hwQ2RpUXZlU0EKLS0tIHBMZ3JWN0llVisveU9yOC9OT0Jq
        cCtFQ3UrU29SZXFvMFV5VjhJRkxSbFkKlZsdKiqXqgegYDXQ88l1kfARzudytKhU
        nDevyL8DudAB2DfDBI8ANDjPGWEB6vpWCpjVLOK8hfD9bJrcpInQBQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:55:35Z"
  mac: ENC[AES256_GCM,data:XVCsCi8BJtHud0xlZV/SVvvc40xoc+OWNHLiDriI4YwlaK0+gXgmXBUwoo6DzTo0N8mkT7TTEE1PiVIKgyv6To6szp4cs7bTAkL3qYheO9dE1pmYOjDKOZgeFZoabCi8/6jqTvaIdQLwaJH8HyTeq69RRkTCeelTRB/srVto13I=,iv:kTff3uPNX/AqNxGAGGyaACY/Io682HFlj9QSxaMinVQ=,tag:cbdeMBA/1+nIIDLgMpFeBw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
