---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sonarr
spec:
  chartRef:
    kind: OCIRepository
    name: sonarr
  interval: 1h
  values:
    controllers:
      sonarr:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/home-operations/sonarr
              tag: 4.0.17.2953@sha256:83607d2b741ec9469db09489e88c473ae6fdf7d85f3b55d4fa809b43e25a2a6c
            env:
              SONARR__APP__INSTANCENAME: Sonarr
              SONARR__APP__THEME: dark
              SONARR__AUTH__METHOD: Forms
              SONARR__AUTH__REQUIRED: Enabled # DisabledForLocalAddresses
              SONARR__LOG__ANALYTICSENABLED: "False"
              SONARR__LOG__LEVEL: info
              SONARR__SERVER__PORT: &port 80
              SONARR__UPDATE__AUTOMATICALLY: "False"
              SONARR__UPDATE__BRANCH: develop
              SONARR__UPDATE__MECHANISM: Docker
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /ping
                    port: *port
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
              seccompProfile: { type: RuntimeDefault }
            resources:
              requests:
                cpu: 100m
                memory: 250Mi
              limits:
                cpu: 1000m
                memory: 1Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 2001 # media-rw
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 2015 # sonarr
        runAsNonRoot: true
        runAsUser: 2015 # sonarr
    service:
      app:
        ports:
          http:
            port: *port
    route:
      internal:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 5Gi
        storageClass: freenas-api-iscsi
      media:
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}-media"
        advancedMounts:
          sonarr:
            app:
              - path: /downloads
                subPath: downloads/complete
              - path: /tv
                subPath: tv
      tmp:
        type: emptyDir
