apiVersion: v1
kind: Secret
metadata:
  name: sonarr-secret
stringData:
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:ksbIZDCRajcG/v+odYiyNhgJqX6FXWjkTrWNvfImAUY=,iv:EWj0xrcVTwflqz48o5pRvkwNyHakGBhb4XYrIlqxtaY=,tag:86JklrO+ZqZhN24St0XDXg==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0YWRBVCsxb2Z2VUFKUisy
        eEJ1OTUraUxYNVFmejNNcGVvYnBPVEtyNFhRCkVqdTVWOE5tOEk4MUd2dGJ1aHVp
        UmNBbDBSRjZJWlIzbWEzbnI2MXFKUFkKLS0tIGo5MGlWWDR0cUYwcUd5aHBpS3Qx
        SmtyWmVlUVVHSUZlVUUxTUFoTUVaSjgK4DvPXb0BbCTEre/DT30U5j0jUdtRdpAc
        rA/QPvRVHO/7R8KyOy1N0lrtLP+YIxyj64pciv8JsQYlWA7BS1Kj9A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-25T01:39:47Z"
  mac: ENC[AES256_GCM,data:10ybcDfgRVnlHP1jwhybYABSiPQFC1A0C2UgLzTdZhJ2dUb7kARodY25d7xihsQArmzwGJ5B84kYOR+ofqDDxUPHtHOp3IZqXe5EfKIe7Vs7t8d4MvbkKjShsFYHCkw94TGysjeSP5BCZGtNrBF06pTxPM1SIykGreUCWl2e6jU=,iv:YHKGx4j8ptXr8VmZxQnDih3t7NY0bDwmtp2IUyzmNYE=,tag:Pt82/pUxgSRwuHYDZDewcw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
