---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-node-exporter

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./prometheus-node-exporter/ks.yaml
