apiVersion: v1
kind: Secret
metadata:
  name: pihole-exporter-secret
stringData:
  PIHOLE_PASSWORD: ENC[AES256_GCM,data:g+gWiapGIizftMS/VDWDDE79sQcRV1ehsnpXftRjG0WgcpaEPHOn8WP7CMc=,iv:awPNDLTBXQ93ueNm3aBBWfnjWqFqIXp78IO11RYKnc4=,tag:8KPzrPy/4jxMQyPSA6o0zg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBieGRxMGthRCtNcCt4Vlpi
        MFduUEZDeHR5MlR2aStqaENlMHZjTVY5TEVBCjBLN1pjVTFkZTMxek9Mb1JDV0FM
        a1NaRmtQNE85ZWhHR2piRHRPQ0I4RW8KLS0tIGJOTjB2enI2c1BMT0ZINEIra2lS
        N3hYbGJxajZvYmp6bUlXTllHa1llcVkKcR9syCVk9QGReyS56WKSKVSo8tcKL5hH
        zqiarSW3ZZRzUjOCvPuubXNSr/jw97M5C0xkzzTgC+Q4BQe8ROnEmA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T02:30:37Z"
  mac: ENC[AES256_GCM,data:mtlBxVfknWIkvh1M82PVqfr/2CiaibfahipcrCb2bRzMhj4IaJRaqx0n3FQnEU+phQnjFp9V/8eTilWi5KSjVUE0MHWG5p6NDP2sTVYdzhlR+taMbjQhoL5sUr1pyYLjFGfoXOl7C3q2iEJUOEIYIQxQjn3G3t3u7B6ECbUubQw=,iv:5hpLPCzoEZCCypXrioxMdErdhLeS3UBa2EDELnfHzu4=,tag:KI9ZOAFOsPE+UfFaO1tB1g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
