apiVersion: v1
kind: Secret
metadata:
  name: pihole-exporter-secret
stringData:
  PIHOLE_PASSWORD: ENC[AES256_GCM,data:UI8cHKLtPYs=,iv:iL1lHRKHFBjEhDGgEhiSOD/akcOHcRb09E2bk1aUHV8=,tag:Q8C2Md0Rtu25YCN4lHoVAg==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3WXA5R3pNRFR4Vi94Z01K
        RGh4QkdLOWdMdUFLNHo4VjhpM3phNnNDWEdnClhyaElsMjhvSG1LbXNBNEdHVDNI
        WlJPa3hyd0FaRTMrOFlDaVp6NzUvMlUKLS0tIFVEcW9xZ0dmZHg2dFBNZmJReUR3
        UVQwV1gyT3NkRDZxc0c5RFFKbjEzVW8KWdWrbv8eN3yoBzJtf87oVuU6yAaLs4km
        oNcX0B8oOPhTkbh1oXryQpIoUR6QJfmK4Yxf3ppYc5BwZJlm7+WMhA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-30T14:11:58Z"
  mac: ENC[AES256_GCM,data:I1T0sxDSZqImfklGFNO3V3aO5fjHoTWl5fMlnUnsI1ru44OKDKX5LbxxdOdlqflsHkqMddt8a9tLX7XAQz3ZpRLa6AvvnHSmtdR6c5XkgvzD6JDVvPRfCukRP6NLLZUKfQP3cekwJmLZXBu5SD/7u9LBHB6n2BEXAGwDIOUk8Fg=,iv:8UYLLtmMLnJ0lOHoU99UJdOJUhKY48vtCmt8KYXGGc8=,tag:mldAoIMqhSLBNM99BgWTxw==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
