---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
spec:
  chartRef:
    kind: OCIRepository
    name: immich
  interval: 1h
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: Deployment
              version: v1
            patch: |
              - op: add
                path: "/metadata/labels/app.ceres.io~1depends-on-postgresql"
                value: "true"
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              tag: v2.7.5
            env:
              IMMICH_MACHINE_LEARNING_URL: '{{ printf "http://%s-machine-learning:3003" .Release.Name }}'
              REDIS_HOSTNAME: '{{ printf "%s-valkey" .Release.Name }}'
              TZ: America/New_York
              DB_USERNAME:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-secret"
                    key: username
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-secret"
                    key: password
              DB_HOSTNAME:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-secret"
                    key: host
              DB_DATABASE_NAME:
                valueFrom:
                  secretKeyRef:
                    name: "{{ .Release.Name }}-db-secret"
                    key: database
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
              seccompProfile: { type: RuntimeDefault }
    defaultPodOptions:
      securityContext:
        fsGroup: 65534
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 65534
        runAsNonRoot: true
        runAsUser: 65534
    immich:
      metrics:
        enabled: true
      persistence:
        library:
          existingClaim: immich-library-pvc
      # ref: https://docs.immich.app/install/config-file
      configuration: # {}
        ffmpeg:
          acceptedVideoCodecs: ["h264", "av1", "hevc", "vp9"]
          targetResolution: "1080"
        machineLearning:
          facialRecognition:
            modelName: "antelopev2"
        trash:
          enabled: true
          days: 30
        server:
          publicUsers: false
          externalDomain: "https://immich.${SECRET_DOMAIN}"
        storageTemplate:
          enabled: true
          template: "{{y}}/{{y}}{{MM}}/{{y}}{{MM}}{{dd}}-{{H}}{{mm}}{{ss}}{{SSS}}"
    valkey:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/valkey-io/valkey
                tag: 9.1-alpine@sha256:a35428eba9043cc0b79dbe54100f0c92784f2de00ad09b01182bfb1c5c83d1bd
      persistence:
        data:
          accessMode: ReadWriteOnce
          enabled: true
          size: 1Gi
          type: emptyDir
    server:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-server
                tag: v2.7.5@sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5
              env:
                IMMICH_PORT: &server-port 2283
          pod:
            securityContext:
              fsGroup: 2001 # media-rw
              fsGroupChangePolicy: OnRootMismatch
              runAsGroup: 65534
              runAsNonRoot: true
              runAsUser: 65534
      service:
        main:
          ports:
            http:
              port: *server-port
      route:
        internal:
          hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
          parentRefs:
            - name: envoy-internal
              namespace: network
              sectionName: https
          rules:
            - backendRefs:
                - identifier: main
                  port: *server-port
      persistence:
        media:
          type: persistentVolumeClaim
          existingClaim: "{{ .Release.Name }}-media"
          advancedMounts:
            main:
              main:
                - path: /photos-kyle
                  subPath: pictures/kyle
                - path: /photos-haley
                  subPath: pictures/haley
                - path: /photos-shared
                  subPath: pictures/shared
    machine-learning:
      enabled: true
      controllers:
        main:
          containers:
            main:
              image:
                repository: ghcr.io/immich-app/immich-machine-learning
                tag: v2.7.5@sha256:a2501141440f10516d329fdfba2c68082e19eb9ba6016c061ac80d23beadf7f3
              env:
                HF_XET_CACHE: /cache/huggingface-xet
                IMMICH_PORT: 3003
                MPLCONFIGDIR: /cache/matplotlib-config
                TRANSFORMERS_CACHE: /cache
      persistence:
        cache:
          accessMode: ReadWriteOnce
          enabled: true
          size: 10Gi
          storageClass: freenas-api-iscsi
          type: persistentVolumeClaim
        tmp:
          type: emptyDir
