---
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-library-pvc
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: freenas-api-nfs

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-media
  namespace: immich
spec:
  storageClassName: ""
  accessModes: ["ReadOnlyMany"]
  resources:
    requests:
      storage: 10Ti
  volumeName: immich-media
