apiVersion: v1
kind: Secret
metadata:
    name: immich-db-secret
stringData:
    database: ENC[AES256_GCM,data:6H6WExRT,iv:ZFY6cd6/Sny/ElUvDYvVcZtyIS8Y0lkWSknyo/Od4Ds=,tag:QZuwyNq19IlcW6+tSpxYmQ==,type:str]
    host: ENC[AES256_GCM,data:Fv1b3/Zw5CWDm+x79JOfa+OL,iv:WYvFFOx5PF4Dmz3za4KIgGpfg58A6hHf7O2UreiojZ0=,tag:8Vkt+xvQZWR43wuzbPqKig==,type:str]
    password: ENC[AES256_GCM,data:PWQS1wuxvA4hAxS2VEC+limGt6L4w35FJCo/FA+FWCLo8J2IfgyAjRs=,iv:5+C0fJeL+2GP4ibkPtdOKPZnCaJabal1i6uQbqky0A4=,tag:xybaqJC2xa5kSMm1oooxRQ==,type:str]
    port: ENC[AES256_GCM,data:08qhhg==,iv:UkJXrhKzR0d3Fl5yodkRs85D12jx0DDIXh7cRIk02Qw=,tag:obS5KQv7BeSqteb8mZobaA==,type:str]
    username: ENC[AES256_GCM,data:aq/AJ8QQ,iv:Uzfc8RPZLSfC5nA+PrmLn1v5CACvJxauTzUAmUzm3U4=,tag:zrgrDt/Riezj61Ty07A7ug==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXE4WEVYZ0hiNEZ3YmQ1
            RVFIQkt4OFJ1VGxVdTB2QndOejFURUxvY1dFCmZvTUg2U0tMOWQ1cDlIQ0loWitE
            WDV3c0xORVFvV3J2U0NWTExDZThYZlEKLS0tIDBDV00yRDNpd3ZSdnQyMWc1QmV4
            L04yd3AwaE9jVVRxaVV5aEZQM1FDMDQKumIhzI5UEwQfa5QQzJoU24UU6NqPzWyI
            NvwPyZkcYksjvdQ+F4iYgf5ztLNY+sH+2LuS7+eUMTfpVIeJsoIpIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-13T20:07:22Z"
    mac: ENC[AES256_GCM,data:7gr3O097bL4xK6uwk6hCcBHv68dcnUk7vR3Jl7fPo8ArXep7o3ltfc81z76TKyFTdGJ9s0Q9sJrnmxmvadglWDyDU+NZQByJUH7dfOWJKcY36SF/or855AUWkoXYXnu1Wwue6oYJhovuFlse8SzLE/BD2ze99l4bj3i6mqb1hfA=,iv:Py8IPxTdiPJVBlAG1slNxO1cY5C8x2a1/n6/qWzkvxc=,tag:K8FJ6KNXCoij6DaqoeGRvg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
