---
# yaml-language-server: $schema=https://raw.githubusercontent.com/semaphoreui/charts/refs/heads/main/stable/semaphore/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: semaphore
spec:
  chartRef:
    kind: OCIRepository
    name: semaphore
  interval: 1h
  values:
    replicaCount: 1
    config:
      # -- List of environment variables to forward into the application environment.
      # Modify this list if additional environment variables need to be accessible.
      forwarded_env_vars: []
    annotations:
      reloader.stakater.com/auto: "true"
    securityContext:
      allowPrivilegeEscalation: false
      capabilities: { drop: ["ALL"] }
      readOnlyRootFilesystem: true
      seccompProfile: { type: RuntimeDefault }
    podSecurityContext:
      fsGroup: 65534
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 65534
      runAsNonRoot: true
      runAsUser: 65534
    extraVolumes:
      - name: tmp
        emptyDir: {}
    extraVolumeMounts:
      - name: tmp
        mountPath: /tmp
        readOnly: false
    general:
      host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
    service:
      port: 3000
    ingress:
      enabled: false # default, use httproute, upcoming release will officially support both
    persistence:
      enabled: true
      size: 10G
      storageClass: freenas-api-iscsi
    database:
      type: postgres
      existingSecret: "{{ .Release.Name }}-db-secret"
      host: semaphore-postgres-rw
      name: semaphore
      passwordKey: password
      port: 5432
      usernameFromSecret: true
      usernameKey: username
    runner:
      existingSecret: "{{ .Release.Name }}-secret"
      tokenKey: runner_token
    admin:
      create: true
      emailKey: admin_email
      existingSecret: "{{ .Release.Name }}-secret"
      fullnameKey: admin_fullname
      passwordKey: admin_password
      usernameKey: admin_username
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 100m
        memory: 64Mi
    envFromSecrets: []
    extraEnvVariables: {}
    extraEnvSecrets: {}
