apiVersion: v1
kind: Secret
metadata:
  name: semaphore-secret
stringData:
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: ENC[AES256_GCM,data:y57AsOCrcIoB3Vs60/8+Yi0rFy1ni2+NLCc9c9ZmTfN3ZNBbktM8pWHr/AJrzQ==,iv:Z3S6Ue6+BR5GbZtTwVhGzNo5pE7LBJwFHiQN+UJZxkI=,tag:7+gJGHsBF/U9oEhUad1dYw==,type:str]
  SEMAPHORE_ADMIN_PASSWORD: ENC[AES256_GCM,data:ZJLd+prFGglbORXOgPnZJpJDWM6gz9ab9c2aKDboHueWA9PF5DZovrpxJm1N,iv:gJr1zzX/iHc86yc2e+F/bkChqClarsHtaR9V38QKEKI=,tag:BREG4oTbMFyd1OMdOluqiw==,type:str]
  SEMAPHORE_COOKIE_ENCRYPTION: ENC[AES256_GCM,data:UA/2oaeCrqLcZeC0QpQAksYCs6ST+RFWY6ej3XRkB7IfQiq08rQzbqcXvXI=,iv:8GgnZYN2uPwdHwBi/Rh7e/HPxsFUxjE9Xtjxtjp/new=,tag:W67VqKP6Tx2a7RRAsdlBVA==,type:str]
  SEMAPHORE_COOKIE_HASH: ENC[AES256_GCM,data:8LFM/ITwHi93n5SNp6/RYQQpowUFBKDoNGnP/mEE96TtPMIQlkgIrOWiKg==,iv:QvLfUkQ1tE9qdValHUaB/2U1zO8867iSG3kPwVpgtr0=,tag:8Hr8CxmuPRzBLocYtTE+lg==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYWJDWXBDUXQyQW5zZGk4
        Z0YrTjdqKzBNWGxETzVtV1ZBMVlPMHFTQUQ4CllucTg5Um1vaDZXVk1EOHZlU1Y0
        UklqcXVBOVVEYk1OUmhER05KUUc4VWsKLS0tIGFPTEFDZStMZFZJdy8yaEhURk16
        QXRQMHc5cmRWZmdUVHZmUmd0cE9OUlEKYJWsw65AaBmRndEhZJOfIFLBizhKyq7/
        Z1XwfkjS7Qy0FhAwKR+xFYATWeKKV9JM/CimFkCEhlP3WJPM/b8xDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T01:57:46Z"
  mac: ENC[AES256_GCM,data:DV+hRVfPxEcjbNclozFmDb9mQGzjDsSKiDv7f8hb+Y6laMBIyYAb86WOqzQlNNoyqvA9RxpPklZcc2X/fIoO8VJHldPWuVC54fportW5CeWlLDpBkq2BEE+7Jlz4oG2Ctgpdk3hfzhxs4YO2RM9DqPXai/uBJCqmOpOZ7u4DHVw=,iv:/Kipq8k69J1x6IxONo9+LtwjdGRc1SjkGcmxloQ0/7s=,tag:p0SKWJwErOc33FpArBC4Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: semaphore-db-secret
stringData:
  database: ENC[AES256_GCM,data:dAMPRjL0BQts,iv:AoPI0yjR+OEt+H1H98LiF6HXuCyrXh5+4UObN/C1Hlg=,tag:zw6EuPMv2Qa2qmmYTl28Ww==,type:str]
  host: ENC[AES256_GCM,data:VN/bt5uvPxgWz3ZE6TmWpwq97GGP,iv:alY4Kkknd0tVxVNvXi5kpg+OlBRxQ+wqSn3KWFfbePU=,tag:E1Vw+eqvW0lu/dWiirRUKA==,type:str]
  password: ENC[AES256_GCM,data:Ri0EYk1LYG0FQD63VM/09RTjc/P6kwGgjTvUSo6C5XtdnI7THeGLfQ==,iv:PJ+IIbRHGEtqhhYxcN4V9PsSlESatQEwlj2+G2XH1N4=,tag:t9W0MYelNhM2WnOMHMZjtw==,type:str]
  port: ENC[AES256_GCM,data:wYIYrw==,iv:hsHHTAWsNreEOIYDgoYJQf3UUkAJv0ZzchCEOK0u60c=,tag:96f+riUHSTlQ5fZrDK3BuQ==,type:str]
  username: ENC[AES256_GCM,data:1En53xMbVFu8,iv:1V45quk9l7sqlzTcasTORDFgSD4fonJl0ObWJAbROVY=,tag:g4z2ylxWKnluM75kWWz9Ag==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArYWJDWXBDUXQyQW5zZGk4
        Z0YrTjdqKzBNWGxETzVtV1ZBMVlPMHFTQUQ4CllucTg5Um1vaDZXVk1EOHZlU1Y0
        UklqcXVBOVVEYk1OUmhER05KUUc4VWsKLS0tIGFPTEFDZStMZFZJdy8yaEhURk16
        QXRQMHc5cmRWZmdUVHZmUmd0cE9OUlEKYJWsw65AaBmRndEhZJOfIFLBizhKyq7/
        Z1XwfkjS7Qy0FhAwKR+xFYATWeKKV9JM/CimFkCEhlP3WJPM/b8xDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T01:57:46Z"
  mac: ENC[AES256_GCM,data:DV+hRVfPxEcjbNclozFmDb9mQGzjDsSKiDv7f8hb+Y6laMBIyYAb86WOqzQlNNoyqvA9RxpPklZcc2X/fIoO8VJHldPWuVC54fportW5CeWlLDpBkq2BEE+7Jlz4oG2Ctgpdk3hfzhxs4YO2RM9DqPXai/uBJCqmOpOZ7u4DHVw=,iv:/Kipq8k69J1x6IxONo9+LtwjdGRc1SjkGcmxloQ0/7s=,tag:p0SKWJwErOc33FpArBC4Ww==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
