apiVersion: v1
kind: Secret
metadata:
  name: semaphore-secret
stringData:
  SEMAPHORE_ACCESS_KEY_ENCRYPTION: ENC[AES256_GCM,data:TeK/34wJQrYoL0CiI0JNjSktyTENPraGT+Xtd+jyDB4jBR94Rt8AEcvSgOg=,iv:6h4t3rIoGofEYFzlW89oKaZ6Fb7Ba3ejaX9OugwhHpo=,tag:rITC50SG1jG1/nr1fY1qZQ==,type:str]
  SEMAPHORE_ADMIN_PASSWORD: ENC[AES256_GCM,data:wGAksr3LPHI9MFQsVOo9CxhzNYf+jUoNrpqd0fSdWdW4f2BB13gbXbjj1IKA,iv:YvEqjsY+/kQXK+8usyP8HjGOAPkCnfJGHhwBMrNQ/Uo=,tag:VcHuj+dbGTfPWfrSC61CmA==,type:str]
  SEMAPHORE_COOKIE_ENCRYPTION: ENC[AES256_GCM,data:JjqDm56ZOLNoFnIywQMwVqrPEP/JKiqVle7S1nXpG3qzJ2hJm7ZSaZLMW/g=,iv:1H9qTw1Sm4OKSQLzlPFFOquh6YOgPOpJBr4IeyoJIsE=,tag:IPSEQz90L3TpR61qNbvLjQ==,type:str]
  SEMAPHORE_COOKIE_HASH: ENC[AES256_GCM,data:h4nqJsERj63ePtVeusSVRIM7gzAfSvn+AnRhgCI19TQu64EwcfTTjqv8NG8=,iv:Ff+amVfL0aRXycH9IQQF4BdHkesKtFi4+j+D8/Sfw7Q=,tag:gukk+pcv1exbQjHO+h7fig==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeGZpREVNT2hTUkU2S0dl
        WmFpZ2h3eVhtMERGQUlGdDRReTV0L0NSc0hFCkZucGtWRzZFK05SOG1FSXlvdDNN
        T2ZvRHhmNkNVNDBHdVJBdkdCK2dmTm8KLS0tIEtKRGZveklyaExxWjVRcTVhUklN
        MjdKS21UbXMybkVOVXNuamtUdXE5VncKhA6uvqHfOitXZF5L9o/w9nUFNcGFVXTI
        2MqML4XrEwera5/37B5qNmaU3cBt0S8OrCChodZPnIQ8Wi3TIpYkgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T11:57:23Z"
  mac: ENC[AES256_GCM,data:1PCRXrB9ETbevHY9OlxzJ7ktVWy3r3ynOaYFjCTRA2G3HfBwcZ1AKeJ8qTETifRje4Uc0ddhcE6TmHPSx6I2gilagdWNph4WJB9oWkzAVGgwZKV5hNv4FXuLkRF3S8B9hFeVy9JNHsI6xPBOhPEPIClT9pHIOG1yvE0jWM7CR7g=,iv:+Mgs917wJdHOQp9BdDLCP0b8G48QDnXA9tZKx16ry10=,tag:r5f5IPo6rk+Lo7im7d86WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: semaphore-db-secret
stringData:
  database: ENC[AES256_GCM,data:QAtF2IxHPpj3,iv:Vs40Ei6+ozcm4X8NF95CUM4Hmmzr1kyYwaoYxcBR0g8=,tag:kU0ZHw4yHE3N0E53kHNYgw==,type:str]
  host: ENC[AES256_GCM,data:YeAzhQVA233mV07V30nx90Z1W3jX,iv:oG/ax037xhF0JQzjY4jvSPCPPn7apzCMszAMH92Ml1E=,tag:xfznwcQ5GtVCRzLwp0XWPA==,type:str]
  password: ENC[AES256_GCM,data:qJCzwupxg0ZLewbzYtxnLZcXW2gKWEB5PdzcauFudrx65L86yyt2UQ==,iv:evykXNdXbfq0aC8zQDfeQ9SuPLzTubEXAgS9a9F+l9c=,tag:Ya3ho+zVXHV7NQsPNUdXhQ==,type:str]
  port: ENC[AES256_GCM,data:He1/ww==,iv:GpwihS/yPalFm1V/6RfrivtM1OCJyfR/bUSH2P4Rofo=,tag:BWcmFhzajNMJYDbpWg/2nQ==,type:str]
  username: ENC[AES256_GCM,data:ME8J5VCHeAST,iv:XLCY7HjkMAMxZOjLXgazT7qNj+0RkwkdiNb/DeuBBwg=,tag:QTLiUD7UZDNjIx+fU5PIZQ==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByeGZpREVNT2hTUkU2S0dl
        WmFpZ2h3eVhtMERGQUlGdDRReTV0L0NSc0hFCkZucGtWRzZFK05SOG1FSXlvdDNN
        T2ZvRHhmNkNVNDBHdVJBdkdCK2dmTm8KLS0tIEtKRGZveklyaExxWjVRcTVhUklN
        MjdKS21UbXMybkVOVXNuamtUdXE5VncKhA6uvqHfOitXZF5L9o/w9nUFNcGFVXTI
        2MqML4XrEwera5/37B5qNmaU3cBt0S8OrCChodZPnIQ8Wi3TIpYkgw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-17T11:57:23Z"
  mac: ENC[AES256_GCM,data:1PCRXrB9ETbevHY9OlxzJ7ktVWy3r3ynOaYFjCTRA2G3HfBwcZ1AKeJ8qTETifRje4Uc0ddhcE6TmHPSx6I2gilagdWNph4WJB9oWkzAVGgwZKV5hNv4FXuLkRF3S8B9hFeVy9JNHsI6xPBOhPEPIClT9pHIOG1yvE0jWM7CR7g=,iv:+Mgs917wJdHOQp9BdDLCP0b8G48QDnXA9tZKx16ry10=,tag:r5f5IPo6rk+Lo7im7d86WQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
