apiVersion: v1
kind: Secret
metadata:
  name: semaphore-secret
stringData:
  admin_email: ENC[AES256_GCM,data:s8Z/EAwmKshcmWMJb7Yh,iv:kQzz9/jIuaUdh8Qxhua50oMKLKlpnikMq4G2e1m4mZw=,tag:VwNrOcyEmU3joZqZ1t6ILQ==,type:str]
  admin_fullname: ENC[AES256_GCM,data:NoOAzWU=,iv:l3BZcLHYRhKjT7lVhgNEVKuURt0wjQdoGplj+B3CFE4=,tag:QWLkcgTrQDnzMRrMEdBXfg==,type:str]
  admin_password: ENC[AES256_GCM,data:69KBAkUepNuvpJPrBizivFnh4HiRCrEGuX9duRfL1x8R65RxVqhJJbfU94yH,iv:WJGodkUZbnmUa+GPgbHEX2S2CaHQRymQVDM599dvdv8=,tag:xg6URWUyfgCC3as7Jmj4dA==,type:str]
  admin_username: ENC[AES256_GCM,data:gbV2Ikk=,iv:fFIPNzdIJt/yV14Iw1ci3NVjwhpAeygc1423SMI17xM=,tag:rTbUkmCqacIeHqEE8LPdBg==,type:str]
  runner_token: ENC[AES256_GCM,data:F+K3WvKQ8dbuY3VnFL30YJaDcvOBYF4eo+EMgDP0QOir49PNJGDcCjyx,iv:GCrysUX3RzeSRirBVTuYiBUafG3IptBMm6f7hU9gy80=,tag:R12pxp0XfI9eI13zrVlXbA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVDJFNmNzRXhtc1ZmS1JU
        Y3R1NVJZZVlsdzhQUFp6VFJQelNhQWljV3hZClkvL0puM0xDOUhpV1pYRW5Mako0
        RmNaWmtaa0ZwQSt2ZWI4bDFxMzRwN3cKLS0tIHFFTG40cGZKWkZZT08xdnhzTGd5
        UmtyZ2E5NHNXT0ZBczRjM3lVdUcvVjAKMj1oB4d7nETG8Eur8fesAkiUDZW0wtaA
        mTQn40PtOE91tShefASccnfVf4FagVinTDQHUKp/vkJuM50SdkNm9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T02:20:07Z"
  mac: ENC[AES256_GCM,data:sQjm+Ql8O8oWRDyJASPweCpxbvg3aK1MCT1Um39qNe/bkfaN6NiYbbSO3ePC1ypoah5hEwcsZLPMKGAhxZPjvs46kXcmRUMMlXb6gNf9UoxeYp85QCH7GC0qKtLM/6n58q7b1EqphWq1/2fr/5Y+mtkXU9nQVlFKmE3JqLAZIPY=,iv:xTXQozA9gxBWAgYLYEP+bQIfZXOXsaIhN63sEZ4iMS0=,tag:VJUYD3NFLLTOuCxq/QxqJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: semaphore-db-secret
stringData:
  database: ENC[AES256_GCM,data:vJAetP5G8fmH,iv:sj/LB46lKHFL6Cfk/KsBn2dj11T7pUKClxo6AruJ4nI=,tag:x+Mp2LKu68WPtl8OlASE+w==,type:str]
  host: ENC[AES256_GCM,data:UxMZMqJw7wfrcaZPXIi1wfO78gaB,iv:uaZbg+cbvMa+PgxxHmfJqf1Ze6OktNPw2j4jOoQJALY=,tag:wAu39vL9Pvhpn+5pt9NNDA==,type:str]
  password: ENC[AES256_GCM,data:uOv0dX+rQvceL9q0J1mceX+uuvbofRMMfy16rCvbSw7KIRd4BFfFTg==,iv:L7C6ND7ViW/gUwt3xMmSttg7tRtWTLg1x220apWCPzg=,tag:QR5oQvEXxF5mRBksteiafA==,type:str]
  port: ENC[AES256_GCM,data:DPJdeQ==,iv:qPBUqf5JJ8PKij+nQx8W+rZYceRXfcLqHe3fqjuemIo=,tag:1Z7EEsED1xsNrQMyJ3eD4Q==,type:str]
  username: ENC[AES256_GCM,data:+53hE2ic87NU,iv:635Yg76Y6KFjwYnxVJD2Gan/VHtY9mTFnTxeG5z7MW0=,tag:PXzNNsr4Hr30LncORh2HHA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBVDJFNmNzRXhtc1ZmS1JU
        Y3R1NVJZZVlsdzhQUFp6VFJQelNhQWljV3hZClkvL0puM0xDOUhpV1pYRW5Mako0
        RmNaWmtaa0ZwQSt2ZWI4bDFxMzRwN3cKLS0tIHFFTG40cGZKWkZZT08xdnhzTGd5
        UmtyZ2E5NHNXT0ZBczRjM3lVdUcvVjAKMj1oB4d7nETG8Eur8fesAkiUDZW0wtaA
        mTQn40PtOE91tShefASccnfVf4FagVinTDQHUKp/vkJuM50SdkNm9g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-16T02:20:07Z"
  mac: ENC[AES256_GCM,data:sQjm+Ql8O8oWRDyJASPweCpxbvg3aK1MCT1Um39qNe/bkfaN6NiYbbSO3ePC1ypoah5hEwcsZLPMKGAhxZPjvs46kXcmRUMMlXb6gNf9UoxeYp85QCH7GC0qKtLM/6n58q7b1EqphWq1/2fr/5Y+mtkXU9nQVlFKmE3JqLAZIPY=,iv:xTXQozA9gxBWAgYLYEP+bQIfZXOXsaIhN63sEZ4iMS0=,tag:VJUYD3NFLLTOuCxq/QxqJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
