apiVersion: v1
kind: Secret
metadata:
  name: pihole-dns-secret
stringData:
  pihole_password: ENC[AES256_GCM,data:Ly7bz+5np03PRs93HFNWCKaT+CAwygc96ZUWHCyLrz3R4+d7Qdpk2Qq4WA4=,iv:0V20u1cMHPkaZbLswofnVWJcXm+1XoYEC/oHREdyo4Y=,tag:fpvid+TT2yCpyruCOL2EkQ==,type:str]
  pihole_server: ENC[AES256_GCM,data:scXKGvvnGtqfQEnA1JxEZM4D,iv:ON5NbUFSHKdd+PS6RaXC2vFoshdpVjwAtuSZJFnUsWY=,tag:7/7SO9gDnPzcB6UuQ4Rd0g==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQekpKYUthWThYK0ZoNkdU
        MStXTHYxRTlxU1czcTdrQllTOXRmemc4SzE4ClkzOW1RV1NPYVBmRUFqTW1oQ2My
        ZWRIVVUwc29namM3UTFZY3VoeUN2Y1kKLS0tIHJOOHU4RzdOdTdpbzZzVUlzWTQr
        UW95NEVSZWdEdXhEU0dXZlYwTnIwQWMKRAzDpIb3BSlCHzeJXB/EKY+hmCkVod9J
        xFve0VfnFG69UEbtm6KZWp0z7D+BuZXFBn41cL7usYAorwMnltEJww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T16:20:06Z"
  mac: ENC[AES256_GCM,data:k6lZUfQCBFivgYkNfuLQjqK4gHGkm2rZ/4E+AevTSxPyV8UXZc9cycRmDFos32iEUZOUQ686K+S7BK2gEe9x5/ogvWmhYhOkBHjnK53QrisIUZ5CNmnKTazqv3Z7Vrr/3pCQ1nVPg4t+YxlQibNvJ7Kpi2srzKtBlTmm0HM3MwU=,iv:+mZtia2ifgdPdHgDW3V31mxDK+JpvI7M+USqpCLHpSs=,tag:cTaNqlCeeRp0z15SEY9K6Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
