apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:xrAEDB0SgZ5yvrdO3kI3khhvBrwG9OBoqHfzlJoNv/KL3N23qLsFPyryFW9eviY/aIXshNo=,iv:RSDqv+D4rOe7vcXDDyM87M/v+sMTVbtskN9NxRo9vhQ=,tag:sMdIIVd6eIOOpI4d3esGmA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuclRNUW1lbHYvODdyZ1RS
        Y3RiTVVNRTZnNWRrRWRVMDUyVzlRalp1eGtzCnpLaVJRY1cxVm9LMzU3NUN6OEl1
        bi9aa2lGMFJrSTRVSEZxemIzNWhNMkkKLS0tIE0ybjhaNk5qcm1ZZ0dUQ0trLzFh
        d1F0QnpPRTNmTXRrKzUxMVF1ZG1mblEKrC7vMjfQJjhmjEsjnotQV12cZm3c6WCJ
        UE+YZHVHoqXwh0c2dwmSxf7wuhK2pFwxR22e1law0mvRXGXOua+qFw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-28T13:55:34Z"
  mac: ENC[AES256_GCM,data:eiWGE68Ew6vwhiqpe0P7ZzY/ej1gqW/JmGjViRFtQk+Lx9Ykb5uPzs84QxvQTcaMJl62BMOd9ERsJ3Ws+02ld5RHz+IK4pajpfvLbkibW4aMU2PvRSh5BUGW5PaJMvfbi7miwu24K1G7FseFgKXzHxHGbHa0NGhlMOwkhKNb4ZE=,iv:W7qf/YAw8a2Pawg8mJBTy9XvELTVqE8t0A2A7vHMWeY=,tag:sd/TsTmDKUX3MPYZxHAYng==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
