apiVersion: v1
kind: Secret
metadata:
  name: freenas-api-nfs-driver-config
stringData:
  driver-config-file.yaml: ENC[AES256_GCM,data:uo3zD7ITG9J/RfQaBCuO5C3TWBNQKtVQDFOeS6Lb5JeQLNwO1Oaft1lTPFGibK6Hnsw6lAyD99QLdj5WMmYdUsQ4xwVobTgTg2FNPJHMKUYo5TA8sV7mND71OW4+NXAkyM+DoVO2KqH6MNzUlHt8VWLb7UxxjJ9Ud5xEebzEvc0sEpCKxBntkVbkWb6uQ9E0ytattkKZFd82BcWGICRVpn5OXJUUc+pnHKlfvAIIKHWjnlCyvTz7XTxDMBmtQGCDCsMqYdnAuAusDkIk5zCbgiGxtnRGD1pQb73mi6CCdTw07+inUfyspxlluOw0kd7El4ToCYXwhlqOP5OxDLGYXYV0lU6OmlLpU1AuuZy41NgVZZL8ED2T4n+Hh+3EGzR+xCvG68Q3u5nX2I0eQgtQdc+1blBQT8OQHPnyUUFPIDhpO/xfbOokjKcvU1KQ9dOKXA+Tu4vzHgY3mtzvbowmWOMV6CZEQRlgas5IQ6QMREyzsX1uvUebwgNh/sET70GjpOel+61ba+wcOYmHsM3EfHeN2LeJx8TzwsWDjIYhRhkMnACqddo3D2PcJCjK9IyA1Jsq5pxe2Zn96iaFuXi4uE96muvxdi4t1DZQf6GiZWTdDxw1N6FC3mv8xRyrwMANmsmrj62YfR07MemfXXN/dzoRhxWD93kehI/PcKg25irol+pa6mZyYG/GC2eioF7ParX+r5CDtE1fuB2XLQytBmwiph+v/HfVNc4gdfrXnZOyU2hvJ877trvaPLpXDzTy5GF/i8vt9BXa5l9gsuw1BAcCqKUe1ZtNYU+/avVrcU44V9HQwyimrcR5jiyo3zVsgBXFkuK6KwYKZBnKzS6iocfaqzy3Dfre7YixVciRVK4sO/0TXfxturLXuxcry7olimn5OksHxofxb46r+RvVcVBMPxcUnmig0QKrwXJt2XdFBmcjpFWErEoi1j7LenoITOqlW8h+eHGOTGnC5pDj4EBU9z9eJsYCB+q/a5Is0Rdvz56ij+RkTFhGTquZGo7nKhCrwm2CjwwoCyQxX/ObA3XPAokmmh7g9HEN+XYDSqhfqLqCtC9Xqs8YTkFQwQt/94/by3n9JYinrXfPqYlaS+O1KM3FXsgo9Jhoap5EXmHNd/+NZDMmuvDj75odF1nuNfr7qxSqq4uMtDfxdGGHffAjGMKBA37QXxjEpcqD+JsZwZmO1PR17+wiXzRNqJEwUbJgtMSAyuPupxokmh5wmTW/9w==,iv:ysEm20vwKdD5vHbLhVn9vAdNo7eyX/i5lLaD8xqLTzI=,tag:HP0cYoZTHPI2EdtJsT/xDg==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvRFZvUktxL3RJMkdQUUw0
        U2JIVVEveStQRE1ZZDkwSHhGNjE4aVUxVmxJCnRBR0lXU3Zic2txbmQ2N3A2czd1
        YzBmM0hBVFFUZ1FmUWNEYU5mSkNGS28KLS0tIFVlelZGYlVlMkdUMzlPT29IOEta
        M3NvTng1S0I0R2dKZUVnRUM5d0dqcWcKh4vexDD/VJaHIAwA9gLTCmbYCeTd+ags
        pBE4HMwD7vxQ5C/aqZvoV2eDBa19oKw9eoYERBbOqPz403Ti1zZAyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T16:03:34Z"
  mac: ENC[AES256_GCM,data:YY6o8OQEEGfH7P02J1XcAkLARIalyH3PqncVrktiUZ2qvMLBXLsziELl4cFPyGf+WLfpIctybA+CAKhIpJKlAr2AXgNEPskh8NTlcrV5S7WAVJ5u4RGguVSUFpdW9LAMdxJT6BhFE4CpEBv5lhRcJfCLz5Mx3ts/49+FyaglA7I=,iv:oqshnA1smzVQwLVuhx6MYDC04IZASd1GCL72LMtEKT0=,tag:xJdKkwUNZM7nTqg57xX+yg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
