---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: homebox-postgres
  annotations:
    cnpg.io/hibernation: "off"
spec:
  # https://github.com/cloudnative-pg/postgres-containers/pkgs/container/postgresql/versions?filters%5Bversion_type%5D=tagged
  instances: 2
  affinity:
    enablePodAntiAffinity: true
    podAntiAffinityType: preferred
    topologyKey: kubernetes.io/hostname
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie@sha256:7259c775ce18bdf668f17a68accb78e5bcc8074bbea9c8cdac974a8a8525a173
  bootstrap:
    initdb:
      database: homebox
      owner: homebox
      secret:
        name: homebox-db-secret
  plugins:
    - name: barman-cloud.cloudnative-pg.io
      isWALArchiver: true
      parameters:
        barmanObjectName: rustfs-s3
  storage:
    size: 10Gi
    storageClass: freenas-api-iscsi
