apiVersion: v1
kind: Secret
metadata:
  name: homebox-db-secret
stringData:
  database: ENC[AES256_GCM,data:TKvuJdMxTw==,iv:m/lIIoBkpgyVbFVV8iTXXDi93dMJ4ZAjg9EVy4jedLg=,tag:ukkZGD/s4intMhdZVr+LBg==,type:str]
  host: ENC[AES256_GCM,data:WyDH8SSTBMZpcoU5K6jTVTcMnQ==,iv:/AaXWUFkT5A1+FYo9HE5z5FKx190ZxUMirbP63PbNSE=,tag:O2+ZvNz3e/KMq5gnkkUcWg==,type:str]
  password: ENC[AES256_GCM,data:1py1XZUllo9OzEHlWRnKtXKHKAYzgkG7QpPIlaf74dotAofcu+l4TLJPVA==,iv:QAXnbYxuHDUZGkV0ErSmuJm1F2ljGfgsyfgbHTDWIcw=,tag:ngIgZYsrnUtr3RUdFYtfUA==,type:str]
  port: ENC[AES256_GCM,data:08qhhg==,iv:UkJXrhKzR0d3Fl5yodkRs85D12jx0DDIXh7cRIk02Qw=,tag:obS5KQv7BeSqteb8mZobaA==,type:str]
  username: ENC[AES256_GCM,data:iT54DfWqxA==,iv:C/JYHhSRW/SeTAeX/I0s9gwtEc9VOo6Crv1sikfRiGo=,tag:sB+5Vn88vHL/bNo3uB62EA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXE4WEVYZ0hiNEZ3YmQ1
        RVFIQkt4OFJ1VGxVdTB2QndOejFURUxvY1dFCmZvTUg2U0tMOWQ1cDlIQ0loWitE
        WDV3c0xORVFvV3J2U0NWTExDZThYZlEKLS0tIDBDV00yRDNpd3ZSdnQyMWc1QmV4
        L04yd3AwaE9jVVRxaVV5aEZQM1FDMDQKumIhzI5UEwQfa5QQzJoU24UU6NqPzWyI
        NvwPyZkcYksjvdQ+F4iYgf5ztLNY+sH+2LuS7+eUMTfpVIeJsoIpIg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-09T02:29:10Z"
  mac: ENC[AES256_GCM,data:+3fv/uU4CO7CVr2qGH4EKnOywvD2goGBWIct0HBEK31ObyVx6O4oURE/uYysZwO19KpQABYqKkM1l/zeUg+NWI/2N7j3TRmr8V8JZXl+LRsuA8a+BBHEeZ0Js2ge5wryO6zDjo05MrSuVE6CRIuJEey4BvYUsmH1IYJiuJ4hqQM=,iv:r+Ye2lEC2y8U67U6lPTeF9B4RwYLO3k+IJ5J08qKWAw=,tag:2G+7STqtn5wOrjXtoyp45Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
