apiVersion: v1
kind: Secret
metadata:
    name: homebox-db-secret
stringData:
    database: ENC[AES256_GCM,data:TKvuJdMxTw==,iv:m/lIIoBkpgyVbFVV8iTXXDi93dMJ4ZAjg9EVy4jedLg=,tag:ukkZGD/s4intMhdZVr+LBg==,type:str]
    host: ENC[AES256_GCM,data:WyDH8SSTBMZpcoU5K6jTVTcMnQ==,iv:/AaXWUFkT5A1+FYo9HE5z5FKx190ZxUMirbP63PbNSE=,tag:O2+ZvNz3e/KMq5gnkkUcWg==,type:str]
    password: ENC[AES256_GCM,data:1py1XZUllo9OzEHlWRnKtXKHKAYzgkG7QpPIlaf74dotAofcu+l4TLJPVA==,iv:QAXnbYxuHDUZGkV0ErSmuJm1F2ljGfgsyfgbHTDWIcw=,tag:ngIgZYsrnUtr3RUdFYtfUA==,type:str]
    port: ENC[AES256_GCM,data:08qhhg==,iv:UkJXrhKzR0d3Fl5yodkRs85D12jx0DDIXh7cRIk02Qw=,tag:obS5KQv7BeSqteb8mZobaA==,type:str]
    username: ENC[AES256_GCM,data:iT54DfWqxA==,iv:C/JYHhSRW/SeTAeX/I0s9gwtEc9VOo6Crv1sikfRiGo=,tag:sB+5Vn88vHL/bNo3uB62EA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXE4WEVYZ0hiNEZ3YmQ1
            RVFIQkt4OFJ1VGxVdTB2QndOejFURUxvY1dFCmZvTUg2U0tMOWQ1cDlIQ0loWitE
            WDV3c0xORVFvV3J2U0NWTExDZThYZlEKLS0tIDBDV00yRDNpd3ZSdnQyMWc1QmV4
            L04yd3AwaE9jVVRxaVV5aEZQM1FDMDQKumIhzI5UEwQfa5QQzJoU24UU6NqPzWyI
            NvwPyZkcYksjvdQ+F4iYgf5ztLNY+sH+2LuS7+eUMTfpVIeJsoIpIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T18:19:11Z"
    mac: ENC[AES256_GCM,data:0SHIAF7eFA+nx19853Ols4Mh2Hj28lwbSyIvCWR7ntXIk+hyN9w3oexFb06KmwmZOfAuNHDSl5ZzVYoVsULxVkAyDMj4eDiCPGi5XXlmSBM5zcZKsPYNAVMlajV5S+iAOlMNhcco3Rl/cO3PScuHrEyybvUENsYL2Qi/61cUMc4=,iv:8eTYbemnZqBT2mZq6hRri93F6SpfbA8IBDE0qfWMMh0=,tag:hHX/fUVSCf7VLAyyA6XqYw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
---
apiVersion: v1
kind: Secret
metadata:
    name: homebox-secret
stringData:
    HBOX_AUTH_API_KEY_PEPPER: ENC[AES256_GCM,data:9nb7tuNRqq8VSjnQz79OeKSUAYaGtUrDVkOpUaTWOMU=,iv:2OtRHScZ+q/danEG1OKaW1inmdN7hhtTDIQ3sjIBWQs=,tag:bCgCGZhmyCRKY7k3IaKtiQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2UXE4WEVYZ0hiNEZ3YmQ1
            RVFIQkt4OFJ1VGxVdTB2QndOejFURUxvY1dFCmZvTUg2U0tMOWQ1cDlIQ0loWitE
            WDV3c0xORVFvV3J2U0NWTExDZThYZlEKLS0tIDBDV00yRDNpd3ZSdnQyMWc1QmV4
            L04yd3AwaE9jVVRxaVV5aEZQM1FDMDQKumIhzI5UEwQfa5QQzJoU24UU6NqPzWyI
            NvwPyZkcYksjvdQ+F4iYgf5ztLNY+sH+2LuS7+eUMTfpVIeJsoIpIg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-14T18:19:11Z"
    mac: ENC[AES256_GCM,data:0SHIAF7eFA+nx19853Ols4Mh2Hj28lwbSyIvCWR7ntXIk+hyN9w3oexFb06KmwmZOfAuNHDSl5ZzVYoVsULxVkAyDMj4eDiCPGi5XXlmSBM5zcZKsPYNAVMlajV5S+iAOlMNhcco3Rl/cO3PScuHrEyybvUENsYL2Qi/61cUMc4=,iv:8eTYbemnZqBT2mZq6hRri93F6SpfbA8IBDE0qfWMMh0=,tag:hHX/fUVSCf7VLAyyA6XqYw==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
