apiVersion: v1
kind: Secret
metadata:
    name: zigbee2mqtt-secret
stringData:
    ZIGBEE2MQTT_CONFIG_ADVANCED_EXT_PAN_ID: ENC[AES256_GCM,data:z5NWYOtZ,iv:0Inlz5d2kqOzzZRCYTjr4S3J+MGLvPxYTLLhFu7aDCM=,tag:WcZImD+BGSpUCa+egonsSA==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_PAN_ID: ENC[AES256_GCM,data:AAsP6ReK,iv:bUdBL/igXg9P8f8NjDSh/aRbdQ2qh9cyyn6QYyO1gaU=,tag:noXNhL3UyZxU6O5C88O55A==,type:str]
    ZIGBEE2MQTT_CONFIG_ADVANCED_NETWORK_KEY: ENC[AES256_GCM,data:DJ+6ZU2c,iv:iduSw04jEju8v+HUrxsUnwWq8PbnUWyr6aR/RzVo1s4=,tag:FC0kBTlQdPY9A1fNMHSXNA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHhwaTM5cm5EN0daV0pj
            N2MxQWp5eEVzcjkxWStjaGJlbjlsNmJLblFjClgvcnNHSldZenpWSmovSG44b2RO
            Yy9FS3NzbjlEMVQvZnliYndxYVhNL1EKLS0tIDh1MEVOS2hNNGE5WThVT09na0Ez
            WXU1TVFSNytrc2dTa1U3TCtPenRaeDAKOE/Tq1qVfk6WY209bp1V0Kb4JGXGKjJZ
            ZeTKu5MVnYwFvEX6N3gZoPOaCD9uEya6syGWqNx+hRqovi2WPrSetQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T14:01:51Z"
    mac: ENC[AES256_GCM,data:A38yy3nHdKBQR5oSl1mqwXZosYXXe1TjGogubqCXwtx5SPlM2eYZvEGq4+JvwILMAff73NNc+YR5AmBsS197yCjHOkBEtKnbjHr1deCp+c0AFJWOe7zcJxBSx+dlW94rcC31rLQKHNUHf35RGkywSHFzlt0TzQqobpafQOuag2s=,iv:xCaKbc+TB92VrPFq38YpfF/FN63fDYpTXh8F9v1T00c=,tag:QMbKmHD+RY1qn8azHA9jog==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
