apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secret
stringData:
    HASS_ELEVATION: ENC[AES256_GCM,data:UmZm,iv:HQQ+DLBIcQJBxRg8Bw3aNAk8hjleKrDatgiX0xWPtUs=,tag:tRYXnKo1WoNwhLH9E9Fu/A==,type:str]
    HASS_GOOGLE_SECURE_DEVICES_PIN: ENC[AES256_GCM,data:wneWAg==,iv:y9EIaYFu7i80evd0Z0/2ZU2S/l4kBZZkVdpquylw41o=,tag:2BvREACD8nOYBTkMLjpmkA==,type:str]
    HASS_LATITUDE: ENC[AES256_GCM,data:pnYW09gCwzZ9,iv:mK9fcCZIjDorLGfbXtri2fuuXfbYEgvGJ8PksDZbIP4=,tag:Evq0jmIH3Cyixr9LoyBY0g==,type:str]
    HASS_LONGITUDE: ENC[AES256_GCM,data:MY2CAXRkAWcO/Q==,iv:05uoIu0IrI9ecniNv9SPKcqGzJp9okFSC/Tn3048R9I=,tag:Qfc1jNF1gEaANY2IByPgAA==,type:str]
    HASS_PIRATE_WEATHER_API_KEY: ENC[AES256_GCM,data:Bp4hSkT1qudQs6Gz5qeIJkx1G/rgE7Z9+94xbIDKIxE=,iv:vblmSfXfja0r3XbXIqgCbklrnYWR37Xui7cQAC7LcpY=,tag:LbySK/JTPt86qBFxPENZSw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNOHhwaTM5cm5EN0daV0pj
            N2MxQWp5eEVzcjkxWStjaGJlbjlsNmJLblFjClgvcnNHSldZenpWSmovSG44b2RO
            Yy9FS3NzbjlEMVQvZnliYndxYVhNL1EKLS0tIDh1MEVOS2hNNGE5WThVT09na0Ez
            WXU1TVFSNytrc2dTa1U3TCtPenRaeDAKOE/Tq1qVfk6WY209bp1V0Kb4JGXGKjJZ
            ZeTKu5MVnYwFvEX6N3gZoPOaCD9uEya6syGWqNx+hRqovi2WPrSetQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-28T02:30:54Z"
    mac: ENC[AES256_GCM,data:FyqVpA7MOXsB1cnbw/lZJCipPm4lHVnKZFAaWogcrnNQpR6T3NALwpS29y5GLyHMhfjFKKBIdLkq2J4sA2R/nsvh4d9tSV8c+NwpQEDwd57KDArAU/stwKRd3SFIX7c8wlSuipQzX/0ly01zUjy3eTvT6WIl4hwshuavvhfq68Q=,iv:d2hAGYm7WtB5gfQrHbOeYEw3bP+Uom98gWeLn7eeKMU=,tag:g8TnGM5fUhxDasZCXwIxpg==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
