---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-test
  namespace: sabnzbd
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 100Gi
  volumeName: nfs-test
