---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Release.Name }}-media"
  namespace: sabnzbd
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 2Ti
  volumeName: "{{ .Release.Name }}-media"
