---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sabnzbd-media
  namespace: sabnzbd
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Ti
  volumeName: sabnzbd-media
