apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:2SveKKE5E3MUx/aGLR5x2389xxN2ARQDzCijea1h2mg=,iv:v/94P241AIfyTAcYNHYvDpdv7lr4gaFcMDQCO+6qJWs=,tag:IczjOQwPhrIMe/yju69Seg==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:1i1GoAld6MnV47R1BrPl7/yFYQYqLBXDJRYO5cC8zOQ=,iv:PougejnxsepMHSR0K5GWXDoRnjjby6uNzV6fUnyTV68=,tag:3yydJy5TypcVkn98y3kfsw==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN1FjYUhXVkJjbkxaK3Nz
        RUsvVEdKa3NsWVExTmpoUWh2a3paN1JoRjBzCjdxdHN1Tk9wSUM0TGp5TDd5TEJQ
        YVhWUjZqMExvdk1Jc1hLM2pBckRMOFUKLS0tIHNRbi8zSXN0cDJRdkpOYzdXRWVM
        Q1VtbWtJNWdCUDQ0enRzazVkM0dxQzgKFR6JwVT4GItlZU18szrbANw89m1H6fci
        qG5co5yiuP5fq1f4w62YSNn2drZJwCH5rgK9QcG1zhZIBIsX1r6CFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T00:14:10Z"
  mac: ENC[AES256_GCM,data:Mb3cr7dXYh6lNINhk+NKPMpnPD9FOJOy+19iqf7QqYouF1gWSHfxfQsktjhZfZLWKctmIJBsGgsaKxpdPH2cAkihkoqDn7GUHABxZjU4hsyLelSLNog5ziYTElTlVfMpZEOgUoVs3c1rplabPoSDiTA3MzTyfrzhn6SNfFto/P4=,iv:OiyM9SL01XfrOSy+OZ1RAI1aQIDE8Bh7ecnzEXtGMbY=,tag:ww1cbJzi9SeuYRNfEt6lAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:4lPb6b40maFh7v8ycyn0daS1z4KStfoyOBo7I32fXXD9IG0C/MnQS0e6W1w=,iv:cHpVi3YyQ8rWPzw2IKmqlrmE47sZrWslo/hUOjg4FJ0=,tag:5SJOL0Uik+3BO/c9ehHm9g==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYN1FjYUhXVkJjbkxaK3Nz
        RUsvVEdKa3NsWVExTmpoUWh2a3paN1JoRjBzCjdxdHN1Tk9wSUM0TGp5TDd5TEJQ
        YVhWUjZqMExvdk1Jc1hLM2pBckRMOFUKLS0tIHNRbi8zSXN0cDJRdkpOYzdXRWVM
        Q1VtbWtJNWdCUDQ0enRzazVkM0dxQzgKFR6JwVT4GItlZU18szrbANw89m1H6fci
        qG5co5yiuP5fq1f4w62YSNn2drZJwCH5rgK9QcG1zhZIBIsX1r6CFQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-14T00:14:10Z"
  mac: ENC[AES256_GCM,data:Mb3cr7dXYh6lNINhk+NKPMpnPD9FOJOy+19iqf7QqYouF1gWSHfxfQsktjhZfZLWKctmIJBsGgsaKxpdPH2cAkihkoqDn7GUHABxZjU4hsyLelSLNog5ziYTElTlVfMpZEOgUoVs3c1rplabPoSDiTA3MzTyfrzhn6SNfFto/P4=,iv:OiyM9SL01XfrOSy+OZ1RAI1aQIDE8Bh7ecnzEXtGMbY=,tag:ww1cbJzi9SeuYRNfEt6lAw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
