apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:2NyAupET94lZ9rSg1BaSb3kvoabJ/0/1ri7ReD0eHRc=,iv:GJX+Kt7GdfaqpOPNF0aVa05YJ/wR9skxtJ7HGEOPp4U=,tag:QMKtIUU76BAdQWilBVj9wg==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:15/acLJHDfVMR48m2A5FCjzl79qjmgOa7qlkOFkwnAw=,iv:6h3K80003zUR2nCAbeuaXjqcfwhJFPjg2P8FaVtO+tI=,tag:8g67RY7yVkzacWCl7ihhLg==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWEUyMmVkbUw4Y2JyZ1Ix
        V0htaWkyekpQWFRIMjI1R1U3WG9kcTBEdVU0ClN2ZWlRblF2WWhCWmNyUnlBbW4z
        b1Jnb3ZSVUZYd0dNQXZ2a05ReHdIT3MKLS0tIDZiZnJ3NTBvSzNRM1B3OGZxRmZB
        UE1wTmN2ZEtNcGZ1dmk5alRuVmk1alkKDfuViQHez+rm+1iPHZyBq36Ders1Qg1Y
        sKgTlCYbJML5hZ3Ba29QYyHupNSTG9aI+zu1kj7PaB2RZ0p2DkJ6dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T22:23:53Z"
  mac: ENC[AES256_GCM,data:Ofm8mJ79OPxG//XD9ILuaYRu+5VW5WRqdZu7ygNq6fbBdL988ljmURnXWz+brKxzYRi/aTp+vNc5NYEzXjdSEZlGngy6jzH/r1qHBfTM7f8TyQAitnVGDnZQDOhUZro82wwmPjEWVMVjQ1OQ9v4wbChPurfZUsNYVqGM3Gz4aMo=,iv:PyMd+FBkwqvKoBOpUPR7ucoZ9lcQu9Cm9VB+vffM3JQ=,tag:0IflerKeLYjP/trqM7uHEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
---
apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-gluetun-secret
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:R43541LUaaj6VroKkDc2Xw+ua+5OtoTXvxiIAneu0u00D+VCF+Athlf+uRk=,iv:3Gvd2WvDLkewyolofk7tI6H0cJ0jo7+ad/JZiPjy88k=,tag:XysJFvvVXunDQu6+g4rOqQ==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCWEUyMmVkbUw4Y2JyZ1Ix
        V0htaWkyekpQWFRIMjI1R1U3WG9kcTBEdVU0ClN2ZWlRblF2WWhCWmNyUnlBbW4z
        b1Jnb3ZSVUZYd0dNQXZ2a05ReHdIT3MKLS0tIDZiZnJ3NTBvSzNRM1B3OGZxRmZB
        UE1wTmN2ZEtNcGZ1dmk5alRuVmk1alkKDfuViQHez+rm+1iPHZyBq36Ders1Qg1Y
        sKgTlCYbJML5hZ3Ba29QYyHupNSTG9aI+zu1kj7PaB2RZ0p2DkJ6dg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-13T22:23:53Z"
  mac: ENC[AES256_GCM,data:Ofm8mJ79OPxG//XD9ILuaYRu+5VW5WRqdZu7ygNq6fbBdL988ljmURnXWz+brKxzYRi/aTp+vNc5NYEzXjdSEZlGngy6jzH/r1qHBfTM7f8TyQAitnVGDnZQDOhUZro82wwmPjEWVMVjQ1OQ9v4wbChPurfZUsNYVqGM3Gz4aMo=,iv:PyMd+FBkwqvKoBOpUPR7ucoZ9lcQu9Cm9VB+vffM3JQ=,tag:0IflerKeLYjP/trqM7uHEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
