apiVersion: v1
kind: Secret
metadata:
  name: sabnzbd-secret
stringData:
  SABNZBD__API_KEY: ENC[AES256_GCM,data:RalPCAXENADYezg7ZqF+d5zd/6f2rkLuMd/tVSwYFDA=,iv:pNkLDqL1odsiptZQu013iq6DlH671woqy5Spe2UjAvw=,tag:PxPILeeC0HvdUKUU6HU56Q==,type:str]
  SABNZBD__NZB_KEY: ENC[AES256_GCM,data:KzZQ8hcYwuhgxTNzUCwz74nonXpmc5JO+0j5zYw8Mvs=,iv:jQ8IShHLBSfmb3NXfr5HbV4VputlkqjW5OV/GhspQDo=,tag:kLP1G+OKTYzUNN1mASnwHA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJbXd5bEZ3Y3N0WmNFaUFT
        eWRUdGJ3cjVPa0pVUXBJRVN3Ym9uZFo2U3lZClZ5VFBoZy9mMENWTVZvK3F3R2Fl
        RHo0ci9YWDV0RnZMcjhKdlhUVGYvcjQKLS0tIGloNU55bGtDbHpzQ3VkT1pabFZm
        NUxyZ0lWMkxNZzExNm50Y0tEaERoUUEKoJJZnm9CFOQ7bdlWubRZb4y9Pwlj2Hha
        kGfzq+2SqRmsbGTxZ8HiMgOGbN3sJUlFYmxBoDbILoQ6tfU/uC44mA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T21:15:32Z"
  mac: ENC[AES256_GCM,data:pegKzS7xmiDF3puzuNOmb+JT/eBGYzhCJ+0TyZE02h4iP/DemodTfmoCuAqYgYJtXq11rrloy7eZFudBpq79VHbFEMCvdIjCf/GHLV+qJ52MIUziuROflY3QQH3u9lbgyhu0YUhSbCduFFOpPC8WjLKwJZggP89WUP5g32NUSZs=,iv:w20p6jGUPnhnbopFxp5iET+SUqXtEt1VMs1Sp6j51PY=,tag:NaYPXUVKk2gCKx8pGCuqUQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
