apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-postgresql-driver-config
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:2UxIr260wSOQssDiczeJqjJ1vGvkIZromHYEDuJfboYKW7515xJk0GIcz0qSETxT894i5JIxD1cHZzGky7BN978p6ZpZbIox45WD14CuS3/n42AcOfL4+5oqA1TMlHFt2Z5YaVrCKXlfN3wf2L9iRFgxIWkR1SpmxvjkRWt5XwkRqVS/1RoBW6r6OzX6uJW9XQUfh+V5cZHHCHNhQq+pj+jXrppFTRuM2RqhafkFHazU6UzEFarKcFpPO+uX3qTs782zD+MchThSWA2n8NK9NR/OFoUqFh17DrCaT5/K0pakIXYrxWmvRw4bgQPdy7KOPgBvSVLL5mhosXcWdj6955ev0zmlUOxF7cF2ZQ5yz8TIB4IRnDuaHIwammUnPU1ZIxX+rnJGiuTmTj2eO6SogJAhsU8tmwpsXw4j+06UV/JRXWLDPsl08bKhR+Gje/J4pSf+WallVE3pQk+n3u2PIy3dUA7aikC+awPHvL3oFO7dN4UfxdUYNZhwpwHBFEXdARdLp47AdVLUcnquXIrXGFGEZBc2kViqYg+O91AbLDZKszilhUvgqB6h1uElQfYYl7SHLIG0jSXJfUZsGhjP+lxIOjos+CacQKtCNGc/oORyr7nZfGoBoNHYMFKInRiV8CRgD4t7uCjukrVC5dOa+0AG48sK7YcW5nIKXXSgTv/FM1I0ICKfHNFAv6w1Er9vi0rky4736LLidCnrLATmQXFYDGND69l/i/8aaNZg7XTZ4Aod6ZNpKFz0umHvFeONIzVaZ8b1rJD9tvOSIUa8igR5hUHrGDR/pVuFC6GoB63g7xKAdH82XXxgzhzkhrjQRHFaT2FDVJkGkJbGuUAJWYTrQPFF6iM3olivYzEglFucT1/mIBw1g+cP3ScCb1Fac1JKwzF5QvxrNtkFcLERcl1kVH//sb52kjxBVTX0DM3ukrh2fHlc0pHkGRItZRtfoV9NJfrMK8T2QkS+M4/0m92X1hP0UYm3UUZkzh9zcwLDDqqYn1m+gDBibm1IgrDcdc1bGxVfwr0BGtyIdwUmxKqbwQN/IsCt7niPIBWobfk9hwCua+kHtj+DhA+6sil55jn9O+ku/GCSBrXMAxr6tGLq3xBquKBGc3dBrPPmx6QM1hIIr3WSrHpD5+p6/Ihwpoi8p4sw/l5eFIxawKAKKvs6H5us0+tF78Hxv9kGveA7iBcqm05P8VJ+77wzNG1ds9mZVCOEBH0Q7+ILYqrP5zzA2/pBi53HPhsqwesVB5ZW3HPsaW69xQwD895vE4SxkB4XIql6x0MT4haPfFb82iLv6ETlEKr849JEteaj67nGa8UgFXcEIFz7f/rilctK8HA90qd0ltYcPQ==,iv:HIzF6Ujb2A0DKcU2hxEMT1gdUdX8wlaYJp0PTpuXzSg=,tag:PH2ouK2rC/dpS2hT8/+rGw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
            SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
            ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
            SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
            n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T01:20:08Z"
    mac: ENC[AES256_GCM,data:ohU9akZQn37KE22QPwbeYyW71bLexMuOoEMZRHMTB1CDk7gOHn9a9ai/9z36XPJZXpxMtIvLtVhJmhGjhTzFt5lNcTDeMjZ/SDJfqof539YS9DbWTLBy6yM9rBBF2J6P/9nnZoTzmtZsRtD1GrMVMsfoo+ToO0JM2zti1eGSawY=,iv:6EwpPLslSkZdkxRpOFbSamkZJSg47DloiqAZaKHLsAY=,tag:N3JsUvwHbMgKZQo+KozOvQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
