apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-postgresql-driver-config
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:tjs1Vo63Z2njSBimYvxd5ElJefFs199DuVTXY3Ttv5ABocb0DJ+wGMPAwClgf1D6YYxT7t3pGesXix9LNnnOHmJ+Pdf7cTdnOZZJqjGqAFR/FccnyfVZPmBefK3fjvONe0Wrflh+iTRRJY2b4Lq0dPpsRff/1mY5VeYlCobBii2ZM+1FFZaCws+VxRHcwGi24DyQuXUMamquRaMudzIIXoZFt9k1zna4O0j7nSJibpNY6R3q/p/l/0wAk1IkpGAc2AZZgXyCZQr4NaeNnB/q8UgfZ5iLarivRPYMRkuBlpbrauCUil54YcgYmZqRJ7q9/AU0lnjA1sfVQAIQYbkROPlBlZRTC3aOaKu5kGbZDAm83wu5oq76Jchli3D/V7t2ebmIcPtsMbW7xr0QuU8vMykXodvgqKWRHyJbhoICYd3fJkkUyDuh4aSAC/USgwyshRQjGE67jidwTETg4hIxuU38nRdYIgLsU68quRVhsaSN6bRuXUL1Oc0bsQRyKa2AaspCPWHodK0zmumGr2zUoS4Ndk7lPUOQ8z851uS/gaLXqBaW/AZhPgWbJYggmkxHAkW//iv9mha0HapohS5oGBHBg+5eIQDLlnVY+0HA63LTBjtB/8Yu+2JWrCI0fdq+jfwG4n2uoq1IFzX5WqK8DWIqDhxL1lLWSPRsswAoU6dSjZ107tKfmigNzFxaijsILz+tWE0DZA/KvZpQfe7ZB2bG18+go503WUVnxE6CNvWdwtt6C2BakFg0EjmGv2kWdj8WrCRaLoMW3RdPMFzIRnW3Jpcalt2vPdncXHnGNe/y9VIFGyDPgEeY5V875KWt3LM1SyGozx55tD4FJKEOK7xxkAOT/818SFn0BQgYa12z6/n1m/J5wwIuu5e/lWUwIPkdYSWT+vG2QPOt2fAxurFcP4iHga6gZDwnF37EtpIqy3Fe8fCIPFvFcUKAcbceFBPW0GMMR33y0lO1Y9bczK5P2JKoZ4QuAxuN75LAqktYmmNisr964HSWnAI/XYpoDgHcgcw7ECndqBt5aHJPfKfMUjq94/9RTVD+WNCHzrk0MP9RWTKuh8HX9sWXzII9+5Mbs1gIucwqRKniawwsEoaekRWkg207dIw+wAblANQcda73tx6zjFQ5lSzoBe5AeLBQBKxgAYVsHGPby4HJjXmiT0r19HroVgntowrhoWkvFhhutxGG16VJQkvhZTODaHTfcCmtcP20HUs02i07rMkc9/nSoLJS93giWp6v7awfQ/LdDMnwx4YlSRIxc7W6cSGEmEBMLdZfRxp/7jOJDwzIAwlP4CRB1G2l3Jc5z2hNFYF3aUCjSr9ZhXgmx7fG2m71QaxE4Qg=,iv:jA9NrTX+6xoTJTnuqGlXdlEFM5pdLZg5UIvj8SuCVxo=,tag:e+AcujmXK2k+OJBlVB+OHQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
            SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
            ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
            SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
            n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T00:44:01Z"
    mac: ENC[AES256_GCM,data:XAh7gpH8N4wGKp88CpDZeNRkvSR3Ou2icO+zEmpwxmor56tPC+rVKIdXEzOaORy14FRwOLdDxRVoiLjgcgZ3U7FGsP6DVGiHPAnCSlyg0fx77gcXvq+77UvnsnpeHO6APAKyZKg0Rrn800A40lyuOdwm5mCKzLB43szQl6uDwpc=,iv:5GUyP7bgqBz0RIGOY4Dvfw17dbRVqyRQGu++Y6LVQPA=,tag:zJgZi3CoU7CCk9+Zpp7GFQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
