apiVersion: v1
kind: Secret
metadata:
    name: freenas-api-iscsi-postgresql-driver-config
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:NeDugZpfXwWqN1rvsLHtOfqdkKy2siUG4QWyTXFda/I8fujBF5eC02xEGTwAYs/STeYupoIomv/xraJJ7qeBE/iHD5IMtXXCA5mI0p6+dtdy0mZjgA959tasQFXhnIxbEts4mO21cKVGgePfVgsjv8HQvspTzCGZ7oJvnqfdcPuUUrTlt2zUFGMlalJz/IsPjUTq1WqKeHgVmF6PtEAr60xvktOAI9mzQgsnxKG2W5kuCjV9WbAcVCkgYI/4oVglhSVM/b+LZwX7JPxWVq/IX9ppY9699q25e2YOGqirfcp7zfDNKRlV3p+I/l2/UxcFJ3mqWyAnINNNC9/keptyUQ5p/o7H1Cv4yjat794kfInJE6IB0o4uKcB2J9qs5tsnxogMwmPYsI/cSkItu0HVl4kmm8x33E05ieoQFQpUA0VBIcfcMlC9uJKGMSildCMFX7+zTslJbCGCGH2ipQwDfQ8Metkwd3y1DV196c/9o9oCasDsh6lK1UqzCUQwLAmnK10tsjV+9lkN6TKCE404cH+gwidZPpuKg3x4rH4UndolY0hkuHDuj2y7zxPo0Z2Wyn/mIugzCaWY1svhA38L8d1A0zRgSoqtzdrG0z9LA4J+bEr7folxMUlJmhbt/801Xja1w32upxVZYuAB6/y0bd/9pia+r1HN3Mr4UUNy+OOqEz8MXZl2q8dCLFjsP6YdZTcDCtGI24T9i9S8ZiiKJrJlXbJZlJsVpyBC/MZL3Swyqs49AiMuC+SXi2Re9us6EC9o3XyqgVelf1MsurtwfemA2qYzNvbbgT5eJRTFVAsUQmiueG74Uv2Q5Oy5Z5WaQ2JXplpsAW8U049S9PuFnx4RyQqzYQ/cfUsCXbh7v80PraflYra0I65L2FwSIDvkhPhpczdONh4EbBcmUd1OQxQmnwFSy46s606Rvxpf6slJEP83rM3bcg9Eo5KfrDAM9153ho7Nnq+v8D6w8PDXsGjhqUXLpLTyswnDsPU/j2NO8HAG1+zJKnL+hGmYsD6ChRGg3w0CvYDIqM5xK6J+8S2Bm/fEUOb2cgHvVYqWTMxnctaxLuijw7mbyp2/tjwVf7Cuqmt6GyrzbQVqly307QOhY/tf3PAALB5bA+WVNg5R6rzNZ5fASWI2gHYUNZdZKBQQ7sdIav3HztXQHby7m1tF4MII1ptK7MNQ6TX5O3JWNP2zZObcKN+fsJ2ah8ZMppIDOpSVJYvaSZqP6LvAURZ1pPA13Y2xYacwNMfh1ag14k68mC+pzv8zuLRrL67HcU30bFk2Nx1CnIk2lpHrua+nQ0lQ17JYVUlPFU5N31zsBCPGPN+BQhFiqEu0sgGwy+eJrQ0EYZA=,iv:LzCgpw0lG0c1L7un5VRKjH0nRUkZiA6yYiKgkHNZRa8=,tag:bDXN+rWSm5uyVtUhOT7cdQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvWHV3L3k3VzNCUFJRSTY2
            SUFhOVFzbnZlMGl5WWlEdXl4blN0OThYWmlFCjVxYjFtbTE3OEtyTVczVnVLSDRH
            ZGFrREZXNmtjMzR5R042YTBjekJpSm8KLS0tIHNhWDRwZEVDNytENkJ1eElJR2k2
            SjVTY2FsUzk1NEFpeHUwOXBLcDgrL2sKbxs1nlrVNl85mmNmchnDIJZYYk94qKZ3
            n+aScjDQ11z90N1cQ80VCxN/W/yxsao4Fq3Clf1to/nCTMaEGL/7sA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-06-08T19:45:23Z"
    mac: ENC[AES256_GCM,data:kzF89pt0VON+i09THgyRRAiRVJ1orBPCaYXp7P0SXiHNesoaaHvz8xVaRQUYMs4sTcZQHeI8G3vF3Ra6cxnrQLUS2PPtr/GMbJhlpKWcZr8+wOrWjAl1nBQTOz0CGFeI/zhPfNQzIh6/T2/rpL/3TQLpCai2y+51Erm2jGv42jc=,iv:s+RfNjPvtDKlBbE5tJwzz1+Bm3GUgOb5HpeovNkq34k=,tag:cq+0vk7SataWr8dRJoHdbQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.1
