apiVersion: v1
kind: Secret
metadata:
    name: renovate-secrets
stringData:
    RENOVATE_TOKEN: ENC[AES256_GCM,data:IUhz9do8jYnNrC0qniuwDcT9dPnpicLQDDSCVBvfIK6iM7yG0NB78A==,iv:e/2HrSxGF/MYQh0hILgwccqCJ9dBADhHiJ/ARRdWsQ4=,tag:hxzriQr300H7EPgqoqMw2A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSXpSNkUvTW16em9wazR1
            T0R1RklGY3ZWcTU0bGRrYmpEMVZpaVlCVlY4CkdWcUQ1b2FKbnVuZVBhWmJpVmdi
            UDVSenVXdkVPdEVINDd4VlBISVRGazAKLS0tIFFRTGE2elRXK0lpLzU2R2dwZG9F
            eFY5NEZQUllMTjlwU0VPakljc2N6QTgKajUi4XnO85TNAmFEwCsqT697f4oxkKD1
            xOcp9fSG9a9UEIfSlMs22WYYpPuJzlg6tUAyzuIcto7ll5+J2XT0CA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-28T17:03:30Z"
    mac: ENC[AES256_GCM,data:Ar4JaNf6Imo5+pHtcvAjzY42dYcXX/oNag5N7gUesSSpXT+OrmqfudRiaLHhrzaclBlgtD3nVw1wDDTPHD80fie64SyyUX/DxwpKsQHABbTtqPUeG60XLvIOM8Sgl6pk0URT2DGhVsUQ9pqAbmYy1A66HylemVijTWJY9PdvnJg=,iv:dA166G9Vllv4dw7mRCcaDwYSdn6rPeq1CKZ89OeRgX4=,tag:4JMap8bxYFWtBf4LzLFGKQ==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
