apiVersion: v1
kind: Secret
metadata:
  name: renovate-secrets
stringData:
  RENOVATE_TOKEN: ENC[AES256_GCM,data:RQ+E19k1MiK8ivAosGPA+a9lj9feZL4PX6vYu63cYhEf1D7j70wawuSNQMD2/3xos1Vv7czxu9m68xJFfrSTXU9e3pXo/ymoluDAsjKV5xBeDq+OSazHEvT+nO/X,iv:7RpYZwIRFfomDpm2MlMUei3GntXlS2nlKoVbsvdnh98=,tag:QEh6yUiwvgIaFHN+LntdaA==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKSXpSNkUvTW16em9wazR1
        T0R1RklGY3ZWcTU0bGRrYmpEMVZpaVlCVlY4CkdWcUQ1b2FKbnVuZVBhWmJpVmdi
        UDVSenVXdkVPdEVINDd4VlBISVRGazAKLS0tIFFRTGE2elRXK0lpLzU2R2dwZG9F
        eFY5NEZQUllMTjlwU0VPakljc2N6QTgKajUi4XnO85TNAmFEwCsqT697f4oxkKD1
        xOcp9fSG9a9UEIfSlMs22WYYpPuJzlg6tUAyzuIcto7ll5+J2XT0CA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T23:52:07Z"
  mac: ENC[AES256_GCM,data:vvGAcSHxlH/3XjCKC+rLm3Eow2XK5DYh3JMtkQUpOaKaXW884ICUa6KqWBXo/hklmcpes+8RJRtpVS8KGR7ZeA36J/nQ4welTzCVf5mGbMdOrUcnMupHJOkPVttxWVZW4aA4ZK7Vc7KUlbVgcKaF7pMQek+8NqvKi6l3sDU+e+4=,iv:qgRPWpDvMniVI687fN0Ue4pQM9QxUfP92rw769xp1cY=,tag:Umm5QQZQmNJZDjEodUQmXw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
