---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: calibre
spec:
  chartRef:
    kind: OCIRepository
    name: calibre
  interval: 1h
  values:
    controllers:
      calibre:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/crocodilestick/calibre-web-automated
              tag: v4.0.6@sha256:c31a738b6d5ec6982c050063dd3f063b6943eb1051fc81144789f840d9093a8d
            env:
              CWA_PORT_OVERRIDE: &port 8083
              NETWORK_SHARE_MODE: true
              # PGID: 2004
              # PUID: 2004
              S6_READ_ONLY_ROOT: "1"
              S6_YES_I_WANT_A_WORLD_WRITABLE_RUN_BECAUSE_KUBERNETES: "1"
              TZ: America/New_York
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            lifecycle:
              postStart:
                exec:
                  command: [ "rm /bin/chown ; ln -s /bin/true /bin/chown" ]
            probes:
              liveness:
                enabled: true
                spec:
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                spec:
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities: { drop: ["ALL"] }
              readOnlyRootFilesystem: true
              seccompProfile: { type: RuntimeDefault }
            resources:
              requests:
                cpu: 50m
                memory: 200Mi
              limits:
                cpu: 2000m
                memory: 2Gi
    defaultPodOptions:
      securityContext:
        fsGroup: 2001 # media-rw
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 911 # 2004 # calibre
        runAsNonRoot: true
        runAsUser: 911 # 2004 # calibre
    service:
      app:
        ports:
          http:
            port: *port
    route:
      internal:
        hostnames: ["{{ .Release.Name }}.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 2Gi
        storageClass: freenas-api-iscsi
        globalMounts:
          - path: /config
      media:
        type: persistentVolumeClaim
        existingClaim: "{{ .Release.Name }}-media"
        globalMounts:
          - path: /calibre-library
            subPath: books
          - path: /cwa-book-ingest
            subPath: downloads/complete/servarr/books
      run:
        type: emptyDir
      tmp:
        type: emptyDir
