apiVersion: v1
kind: Secret
metadata:
  name: calibre-secret
stringData:
  HARDCOVER_TOKEN: ENC[AES256_GCM,data:97eFRgUVH8/JFkG80GywFRvqnxLnLOScwb3AXDvuh3Vsk6otBgbPgqQzwHmQhwwea6R4TCQLrFBvE6odQbMnQXSFqoUOeWdm2FqJXxx9Vv3mcBsszuuztfVetfZExkcF41sXQQO3ZrH2K8eNYJXdkAm9YgcioAyU1WwM1spTiMfSoFsR5Af+NZJ57mAcrEsXP19089kQkOoOqndOu7wts/7uzJAuQMkHKttY+8eT8wW6lJqNBH5MpPnQm/JIZdjYXuecf6tuWJiQdA7VgZayaMcZsjBdnb5gvxpxU68m72k0Q7xdjCeJNerjpJtB9Yq4lLWSwucrkjQsYlLhDFbLPrSgN/GyhD8UOFBQQyFgtgkEeEnMJy5myeq+LmLC1bjB6j9hzkz7KxBHvI7cu+6npCQzamS8Kxwul9Ucb/7laJm3NroKTr+4ZnlPOirAI2dY+UrYo8qCFZ7V7VTha/pXCs4ebmL/K/HL1Qw1P9dleJ9uFWQAUMfyb5sbYA4K9TrwQcTNwCUNLzSDPLIyq2Y+PscFLtJcwnPy4OnWL8L1EdfYWB6bft/DboVTrdyWXsozwI57V2VV8DkeeMW/JrT9FUmyS2wR6IxSbQvCNDnZn/hI3FvVhenflywRBgvVODvQL50gcbHrA4JU9depmIrg6lYTv4rvfu7V6X4VCpGOwVsQI9HhNr1vsMq4Sfl5c6SqmdKtPYs=,iv:t6ZXKjx/MRNC1RZK4RY2PR8f7t9O57RzruPEtErftSk=,tag:8uY0Qa+mhIwD8d+03mcRUQ==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvcHNleXR0a0ZGUUV3aWd6
        RklNMUdZdTNBRzN4VkEvS090VndOdTFPcW04CnR6TUpJWVdDcEZOVURKdU0vTkll
        bGFHOTEycWsrSzF2TzA4cTJpanlLQXcKLS0tIDlJc2kxUE9HYzc5M0ZISC9pS2dR
        eDAvRzRSWG1UYXVOcjJUbUZPOW51UkEKZliuk5ZGsK74bEg6kHnaxovYyAxawLvB
        8p6SGAXfibsKPIo4abJy+ZDbuhekgMiQuoeqrci9WnRvxLZdhSYA6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-22T01:31:46Z"
  mac: ENC[AES256_GCM,data:9I+kpL+5B3OMXwDdgftFw7G9hiXH3hO+UvLHf2qE87mMFz0JApTr2WG87oytFcK0qg6xqTRRdnvBJh+ru+rvWquoQjfJYKjs7jny8vg9pw1FC6XM9Ef30tMpAcmZ4i6IP++5uoichMEdR6uUECOZLEK5bpKbjNuW7u/Da7k4OJc=,iv:rpYI8NhGEARBS/VkG03EgqOe0wcXXqfLX3Xcjkqceh0=,tag:uv27K3Mr+Q7vU7ppoKAUow==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
