---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prometheus-adapter

components:
  - ../../components/sops

resources:
  - ./namespace.yaml
  - ./prometheus-adapter/ks.yaml
