apiVersion: v1
kind: Secret
metadata:
  name: grafana-secret
stringData:
  GF_SECURITY_ADMIN_PASSWORD: ENC[AES256_GCM,data:WHIBMzRLdTyjSde1NovKoCBm0CGGsuLWlrD9skIvFIBtHrWLH3VMfe+6Lv8=,iv:kviZhK1dhnmbjplL7PWGVutuM3RDJn7lMmhSVy5gVJw=,tag:PdVpdeqmD/06OvFS35uSjg==,type:str]
  GF_SECURITY_ADMIN_USER: ENC[AES256_GCM,data:EhJP8l4=,iv:YM+KE8biKyXWUL42W5MiA0hxIcMaRChPX1uPp3JW1fU=,tag:4spwaKx6I8Xb5tksEZSzKQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5RTJ6NTBHN2d0Sjl2SUFz
        U0I5K2JoTGs3aXB4dlRMaVRYUUFRSlppWFd3CktGNW1rVkNHZjlCSnk2eFdIQkdh
        Mi96VzdOUGY4Wm5oZnVaUFFZRnBQY1UKLS0tIE9YQU1mbmxKMUs1UVo0UGFhUFpD
        S1QvU1lvbFpNeHdEbHJZbTduVHhUV0kKUknvU1LC6NplgpKY4/kKMrGHiNJ0W84o
        iTZW6I07M47TZp+vEFoLD9OPsLOYPOcICbYpIDLsVahQ8RfyIfx4fw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-09T17:13:21Z"
  mac: ENC[AES256_GCM,data:W4HJYqGgrBTNWmMO6ulV1lwwx53D8i4Qvr6f7uhGArSZ9WdOCpN2JoRL4omYK1bIluDBcPCVXALxQfqqH6ItstLHoBRfxGELaLkbLB4CpwOfBI3Zko0zh69/6rcNuZk+84KIOGgiZA3Ka4hOx1pqX+PNI/2Hzvj71ZLFW86pVdU=,iv:pZMduSH+C0uWc3FzpWdustIMGgzp4tcY8AoUjLNevSw=,tag:WpgecwkcFWnd+GbBvW+Nkg==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
