apiVersion: v1
kind: Secret
metadata:
  name: nebula-sync-env-secret
stringData:
  PRIMARY: ENC[AES256_GCM,data:NTgFr7KEfWPPSqCKuXu/ln9yjMKW3zxy5PAK,iv:FGgoIQP3njzBWRBqTtO6t8sO39QAcWV4hFaCqUhleXw=,tag:VY2GHr8/ekytQWZGqLOAhg==,type:str]
  REPLICAS: ENC[AES256_GCM,data:jO5NiEkBnsIVILk0cFphdqtZj/blw3dsdEDB,iv:L7jZVN8yJ0EM5BZJDZ/1tQtvY2tU0K/9R3Z7UyJA0R0=,tag:SDjPg7H+oTiySN/uGfZA0Q==,type:str]
  FULL_SYNC: ENC[AES256_GCM,data:ZER7gQ==,iv:FGKb7Un3mSw91+Se+JfZvZ1TjgWvMKp1JaG9SxJTyAc=,tag:niu0L2PUy2+uxg9K+tMluQ==,type:str]
  RUN_GRAVITY: ENC[AES256_GCM,data:/FZkYFo=,iv:1G47W2xWcsK64ufYossSpRlKqJIPzsuvmwr2yV7fP14=,tag:4a1emf3K1gpNGI5WT+Tpnw==,type:str]
  TZ: ENC[AES256_GCM,data:rvAyAatviAyjc53u1AnN/w==,iv:n/k0jFSaHi0iIDIvxGX+aB+y/CCvGP70fFs7B1TPhkE=,tag:HFzr5ByBBkJedtVCS33ZcA==,type:str]
  CLIENT_SKIP_TLS_VERIFICATION: ENC[AES256_GCM,data:kzTJ+Q==,iv:ePJ85aG+k+/ohu1Vj+euDKt69PV1gDCG+J/Ppf+Zevw=,tag:kawdOH3k1HHFssN6wizUGA==,type:str]
  CLIENT_TIMEOUT_SECONDS: ENC[AES256_GCM,data:VMU=,iv:IDIpdDP08ntg/1YVfS/i4stVIeC2bc8YMXCypNgq+E4=,tag:34Zluf+sO9mgoWjQla68HQ==,type:str]
  CLIENT_RETRY_DELAY_SECONDS: ENC[AES256_GCM,data:5A==,iv:2LLQkFGyMHYRTgWet2dEQjqQxJcYNk0fO82qQva+0YY=,tag:Y65+SJrlTahYaAa7Y9/k8A==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwZ0dXME1uTjAyV1c3eEV4
        eXREM3hSRmYwVGtXc296bVpzcW9kME82TUI4Cm9GWjFQWk1iMmJUVkQ1MEJLTnA4
        b1I4a201VUp2blpqZHNHMkZWVndUS1UKLS0tIFZUNFdpNWVTejFmRWtzSG5DTHd1
        UXZMSVNwWmpwdjdhMU5YVXl5NFVZNWcKmVVR+hoj0TUK5qM1vFe2eWwwT0wSNBrQ
        OA2WlgnTk+qRkpZbXsiw40s/lNI5WsR0NmiIHU07JaQDBP8cbQejYA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-29T19:57:42Z"
  mac: ENC[AES256_GCM,data:ryENtTpNDL68BG5HLfVY8BLqQaNMh7eE0ww+fuRAzsC90VlC247otgh1DvE61j/ItyQRzOrxVXYoXKZlCxAJfY+2UhHAHeujXRPY/lLCf0br99GHEiU3CG+R/dZuaWB8gNwayIQpeJ+BbF5xAe7ubreAIgpVWi7b/Px9AZXN8Zs=,iv:KAWv6dNr/K2PdTtsmnRW/2pFvO5s+FV6QGW6CtEowDU=,tag:QlXQ4wSCL+M9F2PgsbZejw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
