apiVersion: v1
kind: Secret
metadata:
  name: unpoller-secret
stringData:
  UP_UNIFI_DEFAULT_API_KEY: ENC[AES256_GCM,data:neMz2o7dj6ysyFzoJetY34pN1ml5Iz3khqthr27x6WI=,iv:UiZ+iL1tL+7580QUQAANd0hfA40fExAectcZG/oy4Yo=,tag:uioW/V+G9Wo69ZoBl988JA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHTGYyZDRjSVZlRWQ1YmQ3
        cG5LeFpRMjAveTVWZEhVWDFKbGp5U0tFc0M4CnQ1bmk5Mk1oa01mazdodGxXeWZH
        alMxZ0NWUVR0SE41Vzc4S2g0SUN6K2cKLS0tIFFtZ2RNQldsMEs4R2lHS3IrZXBv
        V3NiQTN5bEp1MzBaYW9QTllqckYrUGsK24egIEcEOr7i+lKGwsxZdUkSC8T9Y64G
        JnWYCoJE1fpaOlePV1HNQIE3dMNk5/8HZQyHHbZxSm5M9rIihZPPoA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-28T02:17:11Z"
  mac: ENC[AES256_GCM,data:XPyDXYBD9oQhqTaccCtsfrgJ9giRtohJWv+NfgwFixnYs015qylCTd4a94L9zD0apkFAAEckpEgropnoBH+Pg73V+SOO16MGuRYvGTJCpRsQjPfm4tz5hmjlCtcj912ozcOkzXbLV7/rlaKBZt56uiCZC8jKVoZhCatISc21CNI=,iv:x/g6cq7qu7Nz87pwfHHvh9HT0eNtmB/1ybCHNywOKMk=,tag:8uqBzqkkhSII1X/dnugEgA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
