apiVersion: v1
kind: Secret
metadata:
  name: grafana-to-ntfy-secret
stringData:
  NTFY_URL: ENC[AES256_GCM,data:AaiHBCFrQRVkf7OyT6JinULTp9yVbcgATDb8/+D9qlIEkLMsrAxeFpQ+5stNmCIuOEapdhnyqXiDFVNOS/k=,iv:1Y4tvVLXcfrwzEm3TrZgi/+6jkJ+Z3QMrL6H+h5iVHU=,tag:KDOLfUbz6GgyqivUZn3fJw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGMVVYZTRRNzBEUU9VUUlN
        Nno0ODJSd1l3RHk3YmQ1QUM3bnVCUXNEMWh3CjFuZ21DL21ya3hib01ML2xtQ2RB
        WEtHZ2VaNEdMSUhMYkFsSldldEc2SDAKLS0tIDA3aDFDVldQL1lLZEIwWUdJb0J0
        Z20wbTJKblpBSWpYdllReVF2c2xvR3MKyVA4yyK8UlrvLCxdG2OV0ewl0uPtHwou
        Sm1EM20+RMGuLlDKEBlm7ZcD05dxTsnRXI3VI4ZTsJXiYLcRRnT+lQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T16:34:18Z"
  mac: ENC[AES256_GCM,data:dK2GZ8DfGb4h6POyO0GQmEYIcIlMx3GYcOQBdSk3JsPiX3uWgc8OJXQba25WP9Mp4Macu+lri0Gk+KdmC/lzXlbvDSJbrXogfLcyOaqqUEzsTn3dAxfA4DEo+OKtA6g7XBe3ao0URIzwzLyPAnNdZ3hLzm2mWSBRIg3bHU3mX18=,iv:d30hjtZCL2OERXu+uG0JzwM2zL6xFNOdl6/hOiyuKgE=,tag:jXd8YO+TSpMUiFY4aI8Fog==,type:str]
  mac_only_encrypted: true
  version: 3.13.0
