apiVersion: v1
kind: Secret
metadata:
  name: tautulli-secret
stringData:
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:+oCqjz9mvumcKI+KNOIldfrfFVpHQvQoc5kpyBkqgMw=,iv:yE8sHB4y1N4LowRX6rd9JU8NdiIHcdQDnZOyI5qHd8s=,tag:SwhCH75IY/ULko6kmHh7ng==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1TFVUT0hSVmNMblI1L0Vw
        S3NWZlJtZmh3YWVsZ3FMWUhReVhnS0l1RkNVCnRBS0g5REFvVEl5SEtVcUlhMG50
        WEYya2haaDRvWmI0ZitoSGpjQ3JzU1UKLS0tIGg5a01neGllOXZXYXRab2dsNWhB
        NTB6WVNQWTBQR0Qvd1pqY0VIV0M1RncKjZJjLgF2/8q3c1XD6Lpq7Zc4XlEkVGiV
        aRRNG5Qq1u9pAZI9q87lABrb7A0qFL7GTjR6UnfufpJMEwPOxQ+teA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T15:48:40Z"
  mac: ENC[AES256_GCM,data:kiKP3RwupIowbxVURqkFn7bEQwlKj+1de4d+X9cik+vet4XH4PRRX2habiBAKI31kSFge275cy3q8qOFNhso0V2p2VMP6M4Xbj4lWiJnIaLWDOiG3MN01Tj0+29Bn4LzgeCBCEjUY3vzRtzZSNQoZecweC42zfxb9LImvRwp1LU=,iv:OS1/Bn+2tYsNBnebuS+oX5qGAG0WUguIvylVPLlncRo=,tag:gA16hnBm10QH46/qjUjRcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
