apiVersion: v1
kind: Secret
metadata:
  name: tautulli-secret
stringData:
  TAUTULLI_API_KEY: ENC[AES256_GCM,data:s9dLhmQGpZwoyCUauh7dxeb3fHUW8SAJXij4F/xh3Y3jRHxpoEW+OHs/SxANJcdsYmJJXpNemSW1mbE7dxMo5Q==,iv:Oi3QhtwxhlYy+aggidYzofzxWxhPIRu80qiQAbCMqfw=,tag:M0dMBFxsffIzKIWjv63++g==,type:str]
sops:
  age:
    - recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1VE9IMURXZkFBempKVC9D
        WUJ5TXJyZFhodVdhbno5aHBTMG85VWluZUdrCk4yS2gxVWRuUGRocHlUaVdjMEYy
        RVhjcWowVDk3R2F0bVV2UUZzUHVQaUEKLS0tIFJ2MUNwSXJFalhMaEtiUW4vY1lR
        REUxMi92Ujhod2RaSFViNUQyUS9RaEkKcyGzkYL2Qjhj7N9ItktbE+wjIo/rSv+i
        ZB+qsCfrBtbWeV+nljEN0fDJr3CHYxYoOvJzJK+SiTFPB43Ncf1PBw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-05T02:49:59Z"
  mac: ENC[AES256_GCM,data:DtMnV4t+BScP3RaAFZAnpgLASo4+TkuXjRDcQl6hsLyy78gUViC5ulEaJwy+q/LCkHWdZRcMOhRMrjv9eJI1aJiX4zFAMK9a/6r4DCKP9tFfz9Xp/vF7QFc5ny4/34wEJJB1tjMMrAp+jTwuAhXZ0iC6lzxSSzKCItrGaAyOx8I=,iv:QGn+pkYMCnv2BOBqu1kS5kIy5wCsMQQ8DwDetlsdNqg=,tag:4rOQEwl1yUlMJdFhnAZIFQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
