apiVersion: v1
kind: Secret
metadata:
  name: recyclarr-secret
stringData:
  RADARR__AUTH__APIKEY: ENC[AES256_GCM,data:3iPuZBP5090rnqs/1/H/TObiuESXW2sLTSVXkL7zfok=,iv:qhGh2YMHOeJ/wRIv+6OLs/7PLc3sKg16u8SYeVj77tk=,tag:HhHlcXCUlcHzQ7RK0aDVbg==,type:str]
  SONARR__AUTH__APIKEY: ENC[AES256_GCM,data:9b+mIO+DOAFFdfLygkGdtm/3xk/zuMeKRHZTImuMaVM=,iv:2E7M50er9U08fT2xu/2PqqShw4x8D8LqaQkgvGoPI/o=,tag:3Y6oRpTsV3lCg/NsUrGC+Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBESDR6UXJhSjljTkFFY0V5
        YjFFTUZiaS9KVHFRdlppcDdGb1RlTTBVK3hNCkdWTld6d2g4eS83Mmk4MTN1akJM
        VWo1NWF3T1NESFVpOEY0OE1uMCs1LzgKLS0tIE10U1UwOGxnbUVwdlJ3bzJzZnRT
        UUloNGNLeUQ3Z2k4OW1sbzhyeU9IK2sK0T7pLDQHQBo+Wf5IjSZItb1j+exvRbV6
        YK3vVZRrv9p5k9E2Sz2Fv8Zo8ikZlHDTCTsqpIVYS34xRXka9YYvig==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1vcetgycw8e62xe34yfu3kqxcxrcrht0ddacvtae9ardxg6qqqyqqskllu6
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-31T02:07:39Z"
  mac: ENC[AES256_GCM,data:neIKtpVFwuDbrFazS+7A9lRhaCdDe0P5lXh02D382Zpo6HsKi7+K0ZyewBGzYSCsu9beTVQpIOgcRX4F82LtgBKyN811Qd1fqDQGYnb+nz73yoxSf2ZY20V0cEVVgI3akCLiggLoTg40BdYQkeKpFcfrAJ1w6n0LzMGGjMJSzNA=,iv:IZLduiiaGQ06kQRbsOkcrODu2IO4+r0iHjRuFGnPM+U=,tag:gI3/7Ahne1Q/IGV3kOGk5g==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
