---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kapowarr-media
  namespace: kapowarr
spec:
  storageClassName: ""
  accessModes: ["ReadWriteMany"]
  resources:
    requests:
      storage: 10Ti
  volumeName: kapowarr-media
